// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.recommendation;

import java.time.LocalDateTime;
import com.aifitness.user.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

@Entity
@Table(name = "recommendations")
public class Recommendation {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @Column(nullable = false)
    private String status;
    @Column(name = "risk_level")
    private String riskLevel;
    @Column(name = "plan_name")
    private String planName;
    private Integer weeks = 12;
    @Column(name = "days_per_week")
    private Integer daysPerWeek;
    @Column(name = "minutes_per_session")
    private Integer minutesPerSession;
    @Column(name = "nutrition_target")
    private String nutritionTarget;
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRiskLevel() {
        return this.riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPlanName() {
        return this.planName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getWeeks() {
        return this.weeks;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getDaysPerWeek() {
        return this.daysPerWeek;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getMinutesPerSession() {
        return this.minutesPerSession;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNutritionTarget() {
        return this.nutritionTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRiskLevel(final String riskLevel) {
        this.riskLevel = riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPlanName(final String planName) {
        this.planName = planName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWeeks(final Integer weeks) {
        this.weeks = weeks;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDaysPerWeek(final Integer daysPerWeek) {
        this.daysPerWeek = daysPerWeek;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMinutesPerSession(final Integer minutesPerSession) {
        this.minutesPerSession = minutesPerSession;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNutritionTarget(final String nutritionTarget) {
        this.nutritionTarget = nutritionTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Recommendation)) return false;
        final Recommendation other = (Recommendation) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$weeks = this.getWeeks();
        final java.lang.Object other$weeks = other.getWeeks();
        if (this$weeks == null ? other$weeks != null : !this$weeks.equals(other$weeks)) return false;
        final java.lang.Object this$daysPerWeek = this.getDaysPerWeek();
        final java.lang.Object other$daysPerWeek = other.getDaysPerWeek();
        if (this$daysPerWeek == null ? other$daysPerWeek != null : !this$daysPerWeek.equals(other$daysPerWeek)) return false;
        final java.lang.Object this$minutesPerSession = this.getMinutesPerSession();
        final java.lang.Object other$minutesPerSession = other.getMinutesPerSession();
        if (this$minutesPerSession == null ? other$minutesPerSession != null : !this$minutesPerSession.equals(other$minutesPerSession)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$riskLevel = this.getRiskLevel();
        final java.lang.Object other$riskLevel = other.getRiskLevel();
        if (this$riskLevel == null ? other$riskLevel != null : !this$riskLevel.equals(other$riskLevel)) return false;
        final java.lang.Object this$planName = this.getPlanName();
        final java.lang.Object other$planName = other.getPlanName();
        if (this$planName == null ? other$planName != null : !this$planName.equals(other$planName)) return false;
        final java.lang.Object this$nutritionTarget = this.getNutritionTarget();
        final java.lang.Object other$nutritionTarget = other.getNutritionTarget();
        if (this$nutritionTarget == null ? other$nutritionTarget != null : !this$nutritionTarget.equals(other$nutritionTarget)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Recommendation;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $weeks = this.getWeeks();
        result = result * PRIME + ($weeks == null ? 43 : $weeks.hashCode());
        final java.lang.Object $daysPerWeek = this.getDaysPerWeek();
        result = result * PRIME + ($daysPerWeek == null ? 43 : $daysPerWeek.hashCode());
        final java.lang.Object $minutesPerSession = this.getMinutesPerSession();
        result = result * PRIME + ($minutesPerSession == null ? 43 : $minutesPerSession.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $riskLevel = this.getRiskLevel();
        result = result * PRIME + ($riskLevel == null ? 43 : $riskLevel.hashCode());
        final java.lang.Object $planName = this.getPlanName();
        result = result * PRIME + ($planName == null ? 43 : $planName.hashCode());
        final java.lang.Object $nutritionTarget = this.getNutritionTarget();
        result = result * PRIME + ($nutritionTarget == null ? 43 : $nutritionTarget.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Recommendation(id=" + this.getId() + ", user=" + this.getUser() + ", status=" + this.getStatus() + ", riskLevel=" + this.getRiskLevel() + ", planName=" + this.getPlanName() + ", weeks=" + this.getWeeks() + ", daysPerWeek=" + this.getDaysPerWeek() + ", minutesPerSession=" + this.getMinutesPerSession() + ", nutritionTarget=" + this.getNutritionTarget() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Recommendation() {
    }
}
