// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.recommendation;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.aifitness.groq.GroqClient;
import com.aifitness.groq.GroqPromptBuilder;
import com.aifitness.recommendation.dto.PlanResponse;
import com.aifitness.user.User;
import com.aifitness.user.UserProfile;
import com.aifitness.user.UserProfileRepository;
import com.aifitness.user.UserRepository;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;

@Service
public class RecommendationService {
    private final RecommendationRepository recommendationRepository;
    private final RecommendationExerciseRepository recommendationExerciseRepository;
    private final ExerciseRepository exerciseRepository;
    private final UserRepository userRepository;
    private final UserProfileRepository userProfileRepository;
    private final GroqClient groqClient;
    private final GroqPromptBuilder promptBuilder;

    @Transactional(readOnly = true)
    public PlanResponse getCurrentPlan(Long userId) {
        Recommendation rec = recommendationRepository.findTopByUserIdOrderByCreatedAtDesc(userId).orElseThrow(() -> new RuntimeException("No plan found"));
        var exercises = recommendationExerciseRepository.findAllByRecommendationId(rec.getId()).stream().map(re -> PlanResponse.PlanExercise.builder().name(re.getExercise().getName()).dayNumber(re.getDayNumber()).orderIndex(re.getOrderIndex()).sets(re.getSets()).reps(re.getReps()).build()).collect(Collectors.toList());
        return PlanResponse.builder().id(rec.getId()).status(rec.getStatus()).riskLevel(rec.getRiskLevel()).planName(rec.getPlanName()).weeks(rec.getWeeks()).daysPerWeek(rec.getDaysPerWeek()).nutritionTarget(rec.getNutritionTarget()).exercises(exercises).build();
    }

    @Transactional
    public Recommendation generatePlan(Long userId, String riskLevel, String recommendationStatus) {
        User user = userRepository.findById(userId).orElseThrow(() -> new RuntimeException("User not found"));
        UserProfile profile = userProfileRepository.findByUserId(userId).orElse(null);
        String profileContext = "";
        if (profile != null) {
            profileContext = String.format("Gender: %s, Height: %s cm, Weight: %s kg", profile.getGender(), profile.getHeightCm(), profile.getCurrentWeightKg());
        }
        List<Exercise> allExercises = exerciseRepository.findAll();
        String safeExercises = allExercises.stream().filter(Exercise::isActive).map(e -> String.format("ID: %d, Name: %s, Category: %s, Primary Muscle: %s", e.getId(), e.getName(), e.getCategory(), e.getPrimaryMuscle())).collect(Collectors.joining("; "));
        var messages = promptBuilder.buildPlanGenerationPrompt(profileContext, safeExercises);
        String aiResponse = groqClient.getChatCompletion(messages);
        Recommendation plan = new Recommendation();
        plan.setUser(user);
        plan.setStatus(recommendationStatus);
        plan.setRiskLevel(riskLevel);
        List<GeneratedExercise> exercisesToSave = new ArrayList<>();
        try {
            String json = aiResponse.trim();
            if (json.startsWith("```json")) {
                json = json.substring(7);
            }
            if (json.endsWith("```")) {
                json = json.substring(0, json.length() - 3);
            }
            json = json.trim();
            ObjectMapper mapper = new ObjectMapper();
            mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
            GeneratedPlan generated = mapper.readValue(json, GeneratedPlan.class);
            plan.setPlanName(generated.getPlanName() != null ? generated.getPlanName() : "Custom AI Plan");
            plan.setWeeks(generated.getWeeks() != null ? generated.getWeeks() : 12);
            plan.setDaysPerWeek(generated.getDaysPerWeek() != null ? generated.getDaysPerWeek() : 4);
            plan.setMinutesPerSession(generated.getMinutesPerSession() != null ? generated.getMinutesPerSession() : 60);
            plan.setNutritionTarget(generated.getNutritionTarget() != null ? generated.getNutritionTarget() : "Calories: 2000, Protein: 130g, Carbs: 220g, Fat: 70g");
            if (generated.getExercises() != null) {
                exercisesToSave = generated.getExercises();
            }
        } catch (Exception e) {
            e.printStackTrace();
            // Fallback default properties
            plan.setPlanName("Custom AI Plan (Fallback)");
            plan.setWeeks(12);
            plan.setDaysPerWeek(4);
            plan.setMinutesPerSession(60);
            plan.setNutritionTarget("Calories: 2000, Protein: 130g, Carbs: 220g, Fat: 70g");
        }
        final Recommendation savedPlan = recommendationRepository.save(plan);
        if (!exercisesToSave.isEmpty()) {
            for (GeneratedExercise ge : exercisesToSave) {
                Exercise exercise = exerciseRepository.findById(ge.getExerciseId()).orElse(null);
                if (exercise != null) {
                    RecommendationExercise re = new RecommendationExercise();
                    re.setRecommendation(savedPlan);
                    re.setExercise(exercise);
                    re.setDayNumber(ge.getDayNumber() != null ? ge.getDayNumber() : 1);
                    re.setOrderIndex(ge.getOrderIndex() != null ? ge.getOrderIndex() : 1);
                    re.setSets(ge.getSets() != null ? ge.getSets() : 3);
                    re.setReps(ge.getReps() != null ? ge.getReps() : "10");
                    recommendationExerciseRepository.save(re);
                }
            }
        } else {
            // Default exercise fallback if AI didn't provide any valid exercises
            if (!allExercises.isEmpty()) {
                int order = 1;
                for (int i = 0; i < Math.min(4, allExercises.size()); i++) {
                    RecommendationExercise re = new RecommendationExercise();
                    re.setRecommendation(savedPlan);
                    re.setExercise(allExercises.get(i));
                    re.setDayNumber(1);
                    re.setOrderIndex(order++);
                    re.setSets(3);
                    re.setReps("10");
                    recommendationExerciseRepository.save(re);
                }
            }
        }
        return savedPlan;
    }


    private static class GeneratedPlan {
        private String planName;
        private Integer weeks;
        private Integer daysPerWeek;
        private Integer minutesPerSession;
        private String nutritionTarget;
        private List<GeneratedExercise> exercises;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public GeneratedPlan() {
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getPlanName() {
            return this.planName;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Integer getWeeks() {
            return this.weeks;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Integer getDaysPerWeek() {
            return this.daysPerWeek;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Integer getMinutesPerSession() {
            return this.minutesPerSession;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getNutritionTarget() {
            return this.nutritionTarget;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public List<GeneratedExercise> getExercises() {
            return this.exercises;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setPlanName(final String planName) {
            this.planName = planName;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setWeeks(final Integer weeks) {
            this.weeks = weeks;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setDaysPerWeek(final Integer daysPerWeek) {
            this.daysPerWeek = daysPerWeek;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setMinutesPerSession(final Integer minutesPerSession) {
            this.minutesPerSession = minutesPerSession;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setNutritionTarget(final String nutritionTarget) {
            this.nutritionTarget = nutritionTarget;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setExercises(final List<GeneratedExercise> exercises) {
            this.exercises = exercises;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof RecommendationService.GeneratedPlan)) return false;
            final RecommendationService.GeneratedPlan other = (RecommendationService.GeneratedPlan) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$weeks = this.getWeeks();
            final java.lang.Object other$weeks = other.getWeeks();
            if (this$weeks == null ? other$weeks != null : !this$weeks.equals(other$weeks)) return false;
            final java.lang.Object this$daysPerWeek = this.getDaysPerWeek();
            final java.lang.Object other$daysPerWeek = other.getDaysPerWeek();
            if (this$daysPerWeek == null ? other$daysPerWeek != null : !this$daysPerWeek.equals(other$daysPerWeek)) return false;
            final java.lang.Object this$minutesPerSession = this.getMinutesPerSession();
            final java.lang.Object other$minutesPerSession = other.getMinutesPerSession();
            if (this$minutesPerSession == null ? other$minutesPerSession != null : !this$minutesPerSession.equals(other$minutesPerSession)) return false;
            final java.lang.Object this$planName = this.getPlanName();
            final java.lang.Object other$planName = other.getPlanName();
            if (this$planName == null ? other$planName != null : !this$planName.equals(other$planName)) return false;
            final java.lang.Object this$nutritionTarget = this.getNutritionTarget();
            final java.lang.Object other$nutritionTarget = other.getNutritionTarget();
            if (this$nutritionTarget == null ? other$nutritionTarget != null : !this$nutritionTarget.equals(other$nutritionTarget)) return false;
            final java.lang.Object this$exercises = this.getExercises();
            final java.lang.Object other$exercises = other.getExercises();
            if (this$exercises == null ? other$exercises != null : !this$exercises.equals(other$exercises)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof RecommendationService.GeneratedPlan;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $weeks = this.getWeeks();
            result = result * PRIME + ($weeks == null ? 43 : $weeks.hashCode());
            final java.lang.Object $daysPerWeek = this.getDaysPerWeek();
            result = result * PRIME + ($daysPerWeek == null ? 43 : $daysPerWeek.hashCode());
            final java.lang.Object $minutesPerSession = this.getMinutesPerSession();
            result = result * PRIME + ($minutesPerSession == null ? 43 : $minutesPerSession.hashCode());
            final java.lang.Object $planName = this.getPlanName();
            result = result * PRIME + ($planName == null ? 43 : $planName.hashCode());
            final java.lang.Object $nutritionTarget = this.getNutritionTarget();
            result = result * PRIME + ($nutritionTarget == null ? 43 : $nutritionTarget.hashCode());
            final java.lang.Object $exercises = this.getExercises();
            result = result * PRIME + ($exercises == null ? 43 : $exercises.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "RecommendationService.GeneratedPlan(planName=" + this.getPlanName() + ", weeks=" + this.getWeeks() + ", daysPerWeek=" + this.getDaysPerWeek() + ", minutesPerSession=" + this.getMinutesPerSession() + ", nutritionTarget=" + this.getNutritionTarget() + ", exercises=" + this.getExercises() + ")";
        }
    }


    private static class GeneratedExercise {
        private Long exerciseId;
        private Integer dayNumber;
        private Integer orderIndex;
        private Integer sets;
        private String reps;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public GeneratedExercise() {
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Long getExerciseId() {
            return this.exerciseId;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Integer getDayNumber() {
            return this.dayNumber;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Integer getOrderIndex() {
            return this.orderIndex;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Integer getSets() {
            return this.sets;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getReps() {
            return this.reps;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setExerciseId(final Long exerciseId) {
            this.exerciseId = exerciseId;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setDayNumber(final Integer dayNumber) {
            this.dayNumber = dayNumber;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setOrderIndex(final Integer orderIndex) {
            this.orderIndex = orderIndex;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setSets(final Integer sets) {
            this.sets = sets;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setReps(final String reps) {
            this.reps = reps;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof RecommendationService.GeneratedExercise)) return false;
            final RecommendationService.GeneratedExercise other = (RecommendationService.GeneratedExercise) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$exerciseId = this.getExerciseId();
            final java.lang.Object other$exerciseId = other.getExerciseId();
            if (this$exerciseId == null ? other$exerciseId != null : !this$exerciseId.equals(other$exerciseId)) return false;
            final java.lang.Object this$dayNumber = this.getDayNumber();
            final java.lang.Object other$dayNumber = other.getDayNumber();
            if (this$dayNumber == null ? other$dayNumber != null : !this$dayNumber.equals(other$dayNumber)) return false;
            final java.lang.Object this$orderIndex = this.getOrderIndex();
            final java.lang.Object other$orderIndex = other.getOrderIndex();
            if (this$orderIndex == null ? other$orderIndex != null : !this$orderIndex.equals(other$orderIndex)) return false;
            final java.lang.Object this$sets = this.getSets();
            final java.lang.Object other$sets = other.getSets();
            if (this$sets == null ? other$sets != null : !this$sets.equals(other$sets)) return false;
            final java.lang.Object this$reps = this.getReps();
            final java.lang.Object other$reps = other.getReps();
            if (this$reps == null ? other$reps != null : !this$reps.equals(other$reps)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof RecommendationService.GeneratedExercise;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $exerciseId = this.getExerciseId();
            result = result * PRIME + ($exerciseId == null ? 43 : $exerciseId.hashCode());
            final java.lang.Object $dayNumber = this.getDayNumber();
            result = result * PRIME + ($dayNumber == null ? 43 : $dayNumber.hashCode());
            final java.lang.Object $orderIndex = this.getOrderIndex();
            result = result * PRIME + ($orderIndex == null ? 43 : $orderIndex.hashCode());
            final java.lang.Object $sets = this.getSets();
            result = result * PRIME + ($sets == null ? 43 : $sets.hashCode());
            final java.lang.Object $reps = this.getReps();
            result = result * PRIME + ($reps == null ? 43 : $reps.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "RecommendationService.GeneratedExercise(exerciseId=" + this.getExerciseId() + ", dayNumber=" + this.getDayNumber() + ", orderIndex=" + this.getOrderIndex() + ", sets=" + this.getSets() + ", reps=" + this.getReps() + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RecommendationService(final RecommendationRepository recommendationRepository, final RecommendationExerciseRepository recommendationExerciseRepository, final ExerciseRepository exerciseRepository, final UserRepository userRepository, final UserProfileRepository userProfileRepository, final GroqClient groqClient, final GroqPromptBuilder promptBuilder) {
        this.recommendationRepository = recommendationRepository;
        this.recommendationExerciseRepository = recommendationExerciseRepository;
        this.exerciseRepository = exerciseRepository;
        this.userRepository = userRepository;
        this.userProfileRepository = userProfileRepository;
        this.groqClient = groqClient;
        this.promptBuilder = promptBuilder;
    }
}
