// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.recommendation;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import com.aifitness.common.ApiResponse;
import com.aifitness.recommendation.dto.PlanResponse;
import com.aifitness.user.User;
import com.aifitness.user.UserRepository;

@RestController
@RequestMapping("/api/v1/recommendations")
public class RecommendationController {
    private final RecommendationService recommendationService;
    private final UserRepository userRepository;

    @GetMapping("/current")
    public ResponseEntity<ApiResponse<PlanResponse>> getCurrentPlan() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String email = ((UserDetails) auth.getPrincipal()).getUsername();
        User user = userRepository.findByEmail(email).orElseThrow(() -> new RuntimeException("User not found"));
        PlanResponse response = recommendationService.getCurrentPlan(user.getId());
        return ResponseEntity.ok(ApiResponse.success(response, "Current plan retrieved"));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RecommendationController(final RecommendationService recommendationService, final UserRepository userRepository) {
        this.recommendationService = recommendationService;
        this.userRepository = userRepository;
    }
}
