// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.recommendation;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

@Entity
@Table(name = "recommendation_exercises")
public class RecommendationExercise {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "recommendation_id", nullable = false)
    private Recommendation recommendation;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "exercise_id", nullable = false)
    private Exercise exercise;
    @Column(name = "day_number")
    private Integer dayNumber;
    @Column(name = "order_index")
    private Integer orderIndex;
    private Integer sets;
    private String reps;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Recommendation getRecommendation() {
        return this.recommendation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Exercise getExercise() {
        return this.exercise;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getDayNumber() {
        return this.dayNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getOrderIndex() {
        return this.orderIndex;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getSets() {
        return this.sets;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getReps() {
        return this.reps;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRecommendation(final Recommendation recommendation) {
        this.recommendation = recommendation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExercise(final Exercise exercise) {
        this.exercise = exercise;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDayNumber(final Integer dayNumber) {
        this.dayNumber = dayNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOrderIndex(final Integer orderIndex) {
        this.orderIndex = orderIndex;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSets(final Integer sets) {
        this.sets = sets;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setReps(final String reps) {
        this.reps = reps;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RecommendationExercise)) return false;
        final RecommendationExercise other = (RecommendationExercise) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$dayNumber = this.getDayNumber();
        final java.lang.Object other$dayNumber = other.getDayNumber();
        if (this$dayNumber == null ? other$dayNumber != null : !this$dayNumber.equals(other$dayNumber)) return false;
        final java.lang.Object this$orderIndex = this.getOrderIndex();
        final java.lang.Object other$orderIndex = other.getOrderIndex();
        if (this$orderIndex == null ? other$orderIndex != null : !this$orderIndex.equals(other$orderIndex)) return false;
        final java.lang.Object this$sets = this.getSets();
        final java.lang.Object other$sets = other.getSets();
        if (this$sets == null ? other$sets != null : !this$sets.equals(other$sets)) return false;
        final java.lang.Object this$recommendation = this.getRecommendation();
        final java.lang.Object other$recommendation = other.getRecommendation();
        if (this$recommendation == null ? other$recommendation != null : !this$recommendation.equals(other$recommendation)) return false;
        final java.lang.Object this$exercise = this.getExercise();
        final java.lang.Object other$exercise = other.getExercise();
        if (this$exercise == null ? other$exercise != null : !this$exercise.equals(other$exercise)) return false;
        final java.lang.Object this$reps = this.getReps();
        final java.lang.Object other$reps = other.getReps();
        if (this$reps == null ? other$reps != null : !this$reps.equals(other$reps)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RecommendationExercise;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $dayNumber = this.getDayNumber();
        result = result * PRIME + ($dayNumber == null ? 43 : $dayNumber.hashCode());
        final java.lang.Object $orderIndex = this.getOrderIndex();
        result = result * PRIME + ($orderIndex == null ? 43 : $orderIndex.hashCode());
        final java.lang.Object $sets = this.getSets();
        result = result * PRIME + ($sets == null ? 43 : $sets.hashCode());
        final java.lang.Object $recommendation = this.getRecommendation();
        result = result * PRIME + ($recommendation == null ? 43 : $recommendation.hashCode());
        final java.lang.Object $exercise = this.getExercise();
        result = result * PRIME + ($exercise == null ? 43 : $exercise.hashCode());
        final java.lang.Object $reps = this.getReps();
        result = result * PRIME + ($reps == null ? 43 : $reps.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "RecommendationExercise(id=" + this.getId() + ", recommendation=" + this.getRecommendation() + ", exercise=" + this.getExercise() + ", dayNumber=" + this.getDayNumber() + ", orderIndex=" + this.getOrderIndex() + ", sets=" + this.getSets() + ", reps=" + this.getReps() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RecommendationExercise() {
    }
}
