// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.auth;

import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.aifitness.auth.dto.AuthResponse;
import com.aifitness.auth.dto.LoginRequest;
import com.aifitness.auth.dto.SignupRequest;
import com.aifitness.config.JwtUtil;
import com.aifitness.user.User;
import com.aifitness.user.UserProfile;
import com.aifitness.user.UserProfileRepository;
import com.aifitness.user.UserRepository;

@Service
public class AuthService {
    private final UserRepository userRepository;
    private final UserProfileRepository userProfileRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtUtil jwtUtil;
    private final AuthenticationManager authenticationManager;

    @Transactional
    public AuthResponse signup(SignupRequest request) {
        if (userRepository.existsByEmail(request.getEmail())) {
            throw new IllegalArgumentException("Email already in use");
        }
        User user = new User();
        user.setEmail(request.getEmail());
        user.setPasswordHash(passwordEncoder.encode(request.getPassword()));
        user = userRepository.save(user);
        UserProfile profile = new UserProfile();
        profile.setUser(user);
        profile.setFullName(request.getFullName());
        userProfileRepository.save(profile);
        String token = jwtUtil.generateToken(user.getEmail(), user.getId());
        return AuthResponse.builder().token(token).userId(user.getId()).name(profile.getFullName()).onboardingComplete(false).build();
    }

    public AuthResponse login(LoginRequest request) {
        authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(request.getEmail(), request.getPassword()));
        User user = userRepository.findByEmail(request.getEmail()).orElseThrow(() -> new IllegalArgumentException("Invalid email or password"));
        UserProfile profile = userProfileRepository.findByUserId(user.getId()).orElse(null);
        String name = profile != null ? profile.getFullName() : "";
        boolean onboardingComplete = profile != null && profile.getDateOfBirth() != null;
        String token = jwtUtil.generateToken(user.getEmail(), user.getId());
        return AuthResponse.builder().token(token).userId(user.getId()).name(name).onboardingComplete(onboardingComplete).build();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AuthService(final UserRepository userRepository, final UserProfileRepository userProfileRepository, final PasswordEncoder passwordEncoder, final JwtUtil jwtUtil, final AuthenticationManager authenticationManager) {
        this.userRepository = userRepository;
        this.userProfileRepository = userProfileRepository;
        this.passwordEncoder = passwordEncoder;
        this.jwtUtil = jwtUtil;
        this.authenticationManager = authenticationManager;
    }
}
