// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.workout;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import com.aifitness.recommendation.Exercise;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

@Entity
@Table(name = "exercise_performances")
public class ExercisePerformance {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "workout_session_id", nullable = false)
    private WorkoutSession workoutSession;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "exercise_id", nullable = false)
    private Exercise exercise;
    @Column(name = "exercise_order", nullable = false)
    private Integer exerciseOrder;
    @Column(name = "planned_sets")
    private Integer plannedSets;
    @Column(name = "completed_sets", nullable = false)
    private Integer completedSets = 0;
    @Column(name = "actual_reps", length = 100)
    private String actualReps;
    @Column(name = "actual_weight_kg", precision = 7, scale = 2)
    private BigDecimal actualWeightKg;
    @Column(name = "perceived_difficulty")
    private Integer perceivedDifficulty;
    @Column(name = "pain_reported", nullable = false)
    private boolean painReported = false;
    @Column(columnDefinition = "TEXT")
    private String notes;
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public WorkoutSession getWorkoutSession() {
        return this.workoutSession;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Exercise getExercise() {
        return this.exercise;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getExerciseOrder() {
        return this.exerciseOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getPlannedSets() {
        return this.plannedSets;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getCompletedSets() {
        return this.completedSets;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getActualReps() {
        return this.actualReps;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getActualWeightKg() {
        return this.actualWeightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getPerceivedDifficulty() {
        return this.perceivedDifficulty;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isPainReported() {
        return this.painReported;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNotes() {
        return this.notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWorkoutSession(final WorkoutSession workoutSession) {
        this.workoutSession = workoutSession;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExercise(final Exercise exercise) {
        this.exercise = exercise;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExerciseOrder(final Integer exerciseOrder) {
        this.exerciseOrder = exerciseOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPlannedSets(final Integer plannedSets) {
        this.plannedSets = plannedSets;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCompletedSets(final Integer completedSets) {
        this.completedSets = completedSets;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setActualReps(final String actualReps) {
        this.actualReps = actualReps;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setActualWeightKg(final BigDecimal actualWeightKg) {
        this.actualWeightKg = actualWeightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPerceivedDifficulty(final Integer perceivedDifficulty) {
        this.perceivedDifficulty = perceivedDifficulty;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPainReported(final boolean painReported) {
        this.painReported = painReported;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNotes(final String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ExercisePerformance)) return false;
        final ExercisePerformance other = (ExercisePerformance) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isPainReported() != other.isPainReported()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$exerciseOrder = this.getExerciseOrder();
        final java.lang.Object other$exerciseOrder = other.getExerciseOrder();
        if (this$exerciseOrder == null ? other$exerciseOrder != null : !this$exerciseOrder.equals(other$exerciseOrder)) return false;
        final java.lang.Object this$plannedSets = this.getPlannedSets();
        final java.lang.Object other$plannedSets = other.getPlannedSets();
        if (this$plannedSets == null ? other$plannedSets != null : !this$plannedSets.equals(other$plannedSets)) return false;
        final java.lang.Object this$completedSets = this.getCompletedSets();
        final java.lang.Object other$completedSets = other.getCompletedSets();
        if (this$completedSets == null ? other$completedSets != null : !this$completedSets.equals(other$completedSets)) return false;
        final java.lang.Object this$perceivedDifficulty = this.getPerceivedDifficulty();
        final java.lang.Object other$perceivedDifficulty = other.getPerceivedDifficulty();
        if (this$perceivedDifficulty == null ? other$perceivedDifficulty != null : !this$perceivedDifficulty.equals(other$perceivedDifficulty)) return false;
        final java.lang.Object this$workoutSession = this.getWorkoutSession();
        final java.lang.Object other$workoutSession = other.getWorkoutSession();
        if (this$workoutSession == null ? other$workoutSession != null : !this$workoutSession.equals(other$workoutSession)) return false;
        final java.lang.Object this$exercise = this.getExercise();
        final java.lang.Object other$exercise = other.getExercise();
        if (this$exercise == null ? other$exercise != null : !this$exercise.equals(other$exercise)) return false;
        final java.lang.Object this$actualReps = this.getActualReps();
        final java.lang.Object other$actualReps = other.getActualReps();
        if (this$actualReps == null ? other$actualReps != null : !this$actualReps.equals(other$actualReps)) return false;
        final java.lang.Object this$actualWeightKg = this.getActualWeightKg();
        final java.lang.Object other$actualWeightKg = other.getActualWeightKg();
        if (this$actualWeightKg == null ? other$actualWeightKg != null : !this$actualWeightKg.equals(other$actualWeightKg)) return false;
        final java.lang.Object this$notes = this.getNotes();
        final java.lang.Object other$notes = other.getNotes();
        if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ExercisePerformance;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isPainReported() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $exerciseOrder = this.getExerciseOrder();
        result = result * PRIME + ($exerciseOrder == null ? 43 : $exerciseOrder.hashCode());
        final java.lang.Object $plannedSets = this.getPlannedSets();
        result = result * PRIME + ($plannedSets == null ? 43 : $plannedSets.hashCode());
        final java.lang.Object $completedSets = this.getCompletedSets();
        result = result * PRIME + ($completedSets == null ? 43 : $completedSets.hashCode());
        final java.lang.Object $perceivedDifficulty = this.getPerceivedDifficulty();
        result = result * PRIME + ($perceivedDifficulty == null ? 43 : $perceivedDifficulty.hashCode());
        final java.lang.Object $workoutSession = this.getWorkoutSession();
        result = result * PRIME + ($workoutSession == null ? 43 : $workoutSession.hashCode());
        final java.lang.Object $exercise = this.getExercise();
        result = result * PRIME + ($exercise == null ? 43 : $exercise.hashCode());
        final java.lang.Object $actualReps = this.getActualReps();
        result = result * PRIME + ($actualReps == null ? 43 : $actualReps.hashCode());
        final java.lang.Object $actualWeightKg = this.getActualWeightKg();
        result = result * PRIME + ($actualWeightKg == null ? 43 : $actualWeightKg.hashCode());
        final java.lang.Object $notes = this.getNotes();
        result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ExercisePerformance(id=" + this.getId() + ", workoutSession=" + this.getWorkoutSession() + ", exercise=" + this.getExercise() + ", exerciseOrder=" + this.getExerciseOrder() + ", plannedSets=" + this.getPlannedSets() + ", completedSets=" + this.getCompletedSets() + ", actualReps=" + this.getActualReps() + ", actualWeightKg=" + this.getActualWeightKg() + ", perceivedDifficulty=" + this.getPerceivedDifficulty() + ", painReported=" + this.isPainReported() + ", notes=" + this.getNotes() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ExercisePerformance() {
    }
}
