// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.workout;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import com.aifitness.recommendation.Exercise;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

@Entity
@Table(name = "workout_plan_exercises")
public class WorkoutPlanExercise {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "workout_plan_id", nullable = false)
    private WorkoutPlan workoutPlan;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "exercise_id", nullable = false)
    private Exercise exercise;
    @Column(name = "day_number", nullable = false)
    private Integer dayNumber;
    @Column(name = "exercise_order", nullable = false)
    private Integer exerciseOrder;
    @Column(name = "target_sets", nullable = false)
    private Integer targetSets;
    @Column(name = "target_reps", nullable = false, length = 50)
    private String targetReps;
    @Column(name = "target_weight_kg", precision = 7, scale = 2)
    private BigDecimal targetWeightKg;
    @Column(name = "rest_seconds")
    private Integer restSeconds;
    @Column(columnDefinition = "TEXT")
    private String notes;
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public WorkoutPlan getWorkoutPlan() {
        return this.workoutPlan;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Exercise getExercise() {
        return this.exercise;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getDayNumber() {
        return this.dayNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getExerciseOrder() {
        return this.exerciseOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getTargetSets() {
        return this.targetSets;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getTargetReps() {
        return this.targetReps;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getTargetWeightKg() {
        return this.targetWeightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getRestSeconds() {
        return this.restSeconds;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNotes() {
        return this.notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWorkoutPlan(final WorkoutPlan workoutPlan) {
        this.workoutPlan = workoutPlan;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExercise(final Exercise exercise) {
        this.exercise = exercise;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDayNumber(final Integer dayNumber) {
        this.dayNumber = dayNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExerciseOrder(final Integer exerciseOrder) {
        this.exerciseOrder = exerciseOrder;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTargetSets(final Integer targetSets) {
        this.targetSets = targetSets;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTargetReps(final String targetReps) {
        this.targetReps = targetReps;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTargetWeightKg(final BigDecimal targetWeightKg) {
        this.targetWeightKg = targetWeightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRestSeconds(final Integer restSeconds) {
        this.restSeconds = restSeconds;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNotes(final String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof WorkoutPlanExercise)) return false;
        final WorkoutPlanExercise other = (WorkoutPlanExercise) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$dayNumber = this.getDayNumber();
        final java.lang.Object other$dayNumber = other.getDayNumber();
        if (this$dayNumber == null ? other$dayNumber != null : !this$dayNumber.equals(other$dayNumber)) return false;
        final java.lang.Object this$exerciseOrder = this.getExerciseOrder();
        final java.lang.Object other$exerciseOrder = other.getExerciseOrder();
        if (this$exerciseOrder == null ? other$exerciseOrder != null : !this$exerciseOrder.equals(other$exerciseOrder)) return false;
        final java.lang.Object this$targetSets = this.getTargetSets();
        final java.lang.Object other$targetSets = other.getTargetSets();
        if (this$targetSets == null ? other$targetSets != null : !this$targetSets.equals(other$targetSets)) return false;
        final java.lang.Object this$restSeconds = this.getRestSeconds();
        final java.lang.Object other$restSeconds = other.getRestSeconds();
        if (this$restSeconds == null ? other$restSeconds != null : !this$restSeconds.equals(other$restSeconds)) return false;
        final java.lang.Object this$workoutPlan = this.getWorkoutPlan();
        final java.lang.Object other$workoutPlan = other.getWorkoutPlan();
        if (this$workoutPlan == null ? other$workoutPlan != null : !this$workoutPlan.equals(other$workoutPlan)) return false;
        final java.lang.Object this$exercise = this.getExercise();
        final java.lang.Object other$exercise = other.getExercise();
        if (this$exercise == null ? other$exercise != null : !this$exercise.equals(other$exercise)) return false;
        final java.lang.Object this$targetReps = this.getTargetReps();
        final java.lang.Object other$targetReps = other.getTargetReps();
        if (this$targetReps == null ? other$targetReps != null : !this$targetReps.equals(other$targetReps)) return false;
        final java.lang.Object this$targetWeightKg = this.getTargetWeightKg();
        final java.lang.Object other$targetWeightKg = other.getTargetWeightKg();
        if (this$targetWeightKg == null ? other$targetWeightKg != null : !this$targetWeightKg.equals(other$targetWeightKg)) return false;
        final java.lang.Object this$notes = this.getNotes();
        final java.lang.Object other$notes = other.getNotes();
        if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof WorkoutPlanExercise;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $dayNumber = this.getDayNumber();
        result = result * PRIME + ($dayNumber == null ? 43 : $dayNumber.hashCode());
        final java.lang.Object $exerciseOrder = this.getExerciseOrder();
        result = result * PRIME + ($exerciseOrder == null ? 43 : $exerciseOrder.hashCode());
        final java.lang.Object $targetSets = this.getTargetSets();
        result = result * PRIME + ($targetSets == null ? 43 : $targetSets.hashCode());
        final java.lang.Object $restSeconds = this.getRestSeconds();
        result = result * PRIME + ($restSeconds == null ? 43 : $restSeconds.hashCode());
        final java.lang.Object $workoutPlan = this.getWorkoutPlan();
        result = result * PRIME + ($workoutPlan == null ? 43 : $workoutPlan.hashCode());
        final java.lang.Object $exercise = this.getExercise();
        result = result * PRIME + ($exercise == null ? 43 : $exercise.hashCode());
        final java.lang.Object $targetReps = this.getTargetReps();
        result = result * PRIME + ($targetReps == null ? 43 : $targetReps.hashCode());
        final java.lang.Object $targetWeightKg = this.getTargetWeightKg();
        result = result * PRIME + ($targetWeightKg == null ? 43 : $targetWeightKg.hashCode());
        final java.lang.Object $notes = this.getNotes();
        result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "WorkoutPlanExercise(id=" + this.getId() + ", workoutPlan=" + this.getWorkoutPlan() + ", exercise=" + this.getExercise() + ", dayNumber=" + this.getDayNumber() + ", exerciseOrder=" + this.getExerciseOrder() + ", targetSets=" + this.getTargetSets() + ", targetReps=" + this.getTargetReps() + ", targetWeightKg=" + this.getTargetWeightKg() + ", restSeconds=" + this.getRestSeconds() + ", notes=" + this.getNotes() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public WorkoutPlanExercise() {
    }
}
