// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.nutrition;

import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import com.aifitness.common.ApiResponse;

@RestController
@RequestMapping("/api/v1/nutrition")
public class NutritionController {
    private final NutritionService nutritionService;

    @GetMapping("/summary")
    public ResponseEntity<ApiResponse<Object>> getSummary(@AuthenticationPrincipal Long userId) {
        NutritionTarget target = nutritionService.getNutritionTarget(userId);
        return ResponseEntity.ok(ApiResponse.success(target, "Nutrition summary retrieved"));
    }

    @GetMapping("/meals")
    public ResponseEntity<ApiResponse<List<Object>>> getMeals() {
        return ResponseEntity.ok(ApiResponse.success(List.of(), "Meals retrieved"));
    }

    @GetMapping("/meals/{id}")
    public ResponseEntity<ApiResponse<Object>> getMealDetails(@PathVariable Long id) {
        return ResponseEntity.ok(ApiResponse.success(null, "Meal details retrieved"));
    }

    @PostMapping("/meals/{id}/eat")
    public ResponseEntity<ApiResponse<Object>> markMealAsEaten(@PathVariable Long id) {
        return ResponseEntity.ok(ApiResponse.success(null, "Meal marked as eaten"));
    }

    @GetMapping("/logs")
    public ResponseEntity<ApiResponse<List<Object>>> getLogs() {
        return ResponseEntity.ok(ApiResponse.success(List.of(), "Nutrition logs retrieved"));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public NutritionController(final NutritionService nutritionService) {
        this.nutritionService = nutritionService;
    }
}
