// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.nutrition;

import java.time.LocalDate;
import com.aifitness.user.User;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

@Entity
@Table(name = "nutrition_targets")
public class NutritionTarget {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    private LocalDate targetDate;
    private Integer caloriesTarget;
    private Integer proteinGramsTarget;
    private Integer carbsGramsTarget;
    private Integer fatGramsTarget;
    private Integer caloriesConsumed = 0;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getTargetDate() {
        return this.targetDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getCaloriesTarget() {
        return this.caloriesTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getProteinGramsTarget() {
        return this.proteinGramsTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getCarbsGramsTarget() {
        return this.carbsGramsTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getFatGramsTarget() {
        return this.fatGramsTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getCaloriesConsumed() {
        return this.caloriesConsumed;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTargetDate(final LocalDate targetDate) {
        this.targetDate = targetDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCaloriesTarget(final Integer caloriesTarget) {
        this.caloriesTarget = caloriesTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProteinGramsTarget(final Integer proteinGramsTarget) {
        this.proteinGramsTarget = proteinGramsTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCarbsGramsTarget(final Integer carbsGramsTarget) {
        this.carbsGramsTarget = carbsGramsTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFatGramsTarget(final Integer fatGramsTarget) {
        this.fatGramsTarget = fatGramsTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCaloriesConsumed(final Integer caloriesConsumed) {
        this.caloriesConsumed = caloriesConsumed;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof NutritionTarget)) return false;
        final NutritionTarget other = (NutritionTarget) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$caloriesTarget = this.getCaloriesTarget();
        final java.lang.Object other$caloriesTarget = other.getCaloriesTarget();
        if (this$caloriesTarget == null ? other$caloriesTarget != null : !this$caloriesTarget.equals(other$caloriesTarget)) return false;
        final java.lang.Object this$proteinGramsTarget = this.getProteinGramsTarget();
        final java.lang.Object other$proteinGramsTarget = other.getProteinGramsTarget();
        if (this$proteinGramsTarget == null ? other$proteinGramsTarget != null : !this$proteinGramsTarget.equals(other$proteinGramsTarget)) return false;
        final java.lang.Object this$carbsGramsTarget = this.getCarbsGramsTarget();
        final java.lang.Object other$carbsGramsTarget = other.getCarbsGramsTarget();
        if (this$carbsGramsTarget == null ? other$carbsGramsTarget != null : !this$carbsGramsTarget.equals(other$carbsGramsTarget)) return false;
        final java.lang.Object this$fatGramsTarget = this.getFatGramsTarget();
        final java.lang.Object other$fatGramsTarget = other.getFatGramsTarget();
        if (this$fatGramsTarget == null ? other$fatGramsTarget != null : !this$fatGramsTarget.equals(other$fatGramsTarget)) return false;
        final java.lang.Object this$caloriesConsumed = this.getCaloriesConsumed();
        final java.lang.Object other$caloriesConsumed = other.getCaloriesConsumed();
        if (this$caloriesConsumed == null ? other$caloriesConsumed != null : !this$caloriesConsumed.equals(other$caloriesConsumed)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$targetDate = this.getTargetDate();
        final java.lang.Object other$targetDate = other.getTargetDate();
        if (this$targetDate == null ? other$targetDate != null : !this$targetDate.equals(other$targetDate)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof NutritionTarget;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $caloriesTarget = this.getCaloriesTarget();
        result = result * PRIME + ($caloriesTarget == null ? 43 : $caloriesTarget.hashCode());
        final java.lang.Object $proteinGramsTarget = this.getProteinGramsTarget();
        result = result * PRIME + ($proteinGramsTarget == null ? 43 : $proteinGramsTarget.hashCode());
        final java.lang.Object $carbsGramsTarget = this.getCarbsGramsTarget();
        result = result * PRIME + ($carbsGramsTarget == null ? 43 : $carbsGramsTarget.hashCode());
        final java.lang.Object $fatGramsTarget = this.getFatGramsTarget();
        result = result * PRIME + ($fatGramsTarget == null ? 43 : $fatGramsTarget.hashCode());
        final java.lang.Object $caloriesConsumed = this.getCaloriesConsumed();
        result = result * PRIME + ($caloriesConsumed == null ? 43 : $caloriesConsumed.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $targetDate = this.getTargetDate();
        result = result * PRIME + ($targetDate == null ? 43 : $targetDate.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "NutritionTarget(id=" + this.getId() + ", user=" + this.getUser() + ", targetDate=" + this.getTargetDate() + ", caloriesTarget=" + this.getCaloriesTarget() + ", proteinGramsTarget=" + this.getProteinGramsTarget() + ", carbsGramsTarget=" + this.getCarbsGramsTarget() + ", fatGramsTarget=" + this.getFatGramsTarget() + ", caloriesConsumed=" + this.getCaloriesConsumed() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public NutritionTarget() {
    }
}
