// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.nutrition;

import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.log;
import java.time.LocalDate;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.aifitness.recommendation.Recommendation;
import com.aifitness.recommendation.RecommendationRepository;
import com.aifitness.user.User;
import com.aifitness.user.UserRepository;

@Service
public class NutritionService {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(NutritionService.class);
    private final NutritionTargetRepository nutritionTargetRepository;
    private final RecommendationRepository recommendationRepository;
    private final UserRepository userRepository;

    @Transactional
    public void createOrUpdateTargetFromPlan(Recommendation plan) {
        if (plan == null || plan.getNutritionTarget() == null) return;
        Long userId = plan.getUser().getId();
        LocalDate today = LocalDate.now();
        NutritionTarget target = nutritionTargetRepository.findByUserIdAndTargetDate(userId, today).orElse(new NutritionTarget());
        target.setUser(plan.getUser());
        target.setTargetDate(today);
        String raw = plan.getNutritionTarget();
        target.setCaloriesTarget(extractInt(raw, "Calories:\\s*(\\d+)"));
        target.setProteinGramsTarget(extractInt(raw, "Protein:\\s*(\\d+)"));
        target.setCarbsGramsTarget(extractInt(raw, "Carbs:\\s*(\\d+)"));
        target.setFatGramsTarget(extractInt(raw, "Fat:\\s*(\\d+)"));
        nutritionTargetRepository.save(target);
        log.info("Saved NutritionTarget for user {} based on recommendation target: {}", userId, raw);
    }

    @Transactional(readOnly = true)
    public NutritionTarget getNutritionTarget(Long userId) {
        LocalDate today = LocalDate.now();
        return nutritionTargetRepository.findByUserIdAndTargetDate(userId, today).orElseGet(() -> {
            Recommendation latest = recommendationRepository.findTopByUserIdOrderByCreatedAtDesc(userId).orElse(null);
            if (latest != null) {
                NutritionTarget target = new NutritionTarget();
                User user = userRepository.findById(userId).orElseThrow(() -> new RuntimeException("User not found"));
                target.setUser(user);
                target.setTargetDate(today);
                String raw = latest.getNutritionTarget();
                target.setCaloriesTarget(extractInt(raw, "Calories:\\s*(\\d+)"));
                target.setProteinGramsTarget(extractInt(raw, "Protein:\\s*(\\d+)"));
                target.setCarbsGramsTarget(extractInt(raw, "Carbs:\\s*(\\d+)"));
                target.setFatGramsTarget(extractInt(raw, "Fat:\\s*(\\d+)"));
                return target;
            }
            NutritionTarget def = new NutritionTarget();
            User user = userRepository.findById(userId).orElseThrow(() -> new RuntimeException("User not found"));
            def.setUser(user);
            def.setTargetDate(today);
            def.setCaloriesTarget(2000);
            def.setProteinGramsTarget(130);
            def.setCarbsGramsTarget(220);
            def.setFatGramsTarget(70);
            return def;
        });
    }

    private Integer extractInt(String source, String regex) {
        try {
            Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
            Matcher matcher = pattern.matcher(source);
            if (matcher.find()) {
                return Integer.parseInt(matcher.group(1));
            }
        } catch (Exception e) {
            log.warn("Failed to extract value from \'{}\' with regex \'{}\'", source, regex);
        }
        return 0;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public NutritionService(final NutritionTargetRepository nutritionTargetRepository, final RecommendationRepository recommendationRepository, final UserRepository userRepository) {
        this.nutritionTargetRepository = nutritionTargetRepository;
        this.recommendationRepository = recommendationRepository;
        this.userRepository = userRepository;
    }
}
