// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.dashboard;

import java.time.LocalTime;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.aifitness.dashboard.dto.DashboardData;
import com.aifitness.progress.ProgressService;
import com.aifitness.progress.dto.ProgressSummary;
import com.aifitness.recommendation.Recommendation;
import com.aifitness.recommendation.RecommendationRepository;
import com.aifitness.user.UserProfile;
import com.aifitness.user.UserProfileRepository;

@Service
public class DashboardService {
    private final UserProfileRepository userProfileRepository;
    private final RecommendationRepository recommendationRepository;
    private final ProgressService progressService;

    @Transactional(readOnly = true)
    public DashboardData getDashboard(Long userId) {
        UserProfile profile = userProfileRepository.findByUserId(userId).orElse(null);
        String name = profile != null ? (profile.getFullName() != null ? profile.getFullName().split(" ")[0] : "User") : "User";
        String greeting = getGreeting();
        // Get recommendation status
        Recommendation rec = recommendationRepository.findTopByUserIdOrderByCreatedAtDesc(userId).orElse(null);
        String recStatus = rec != null ? rec.getStatus() : "PENDING";
        // Get progress summary
        ProgressSummary summary = progressService.getSummary(userId);
        // Compute weekly completion (days per week from profile vs workouts done this week)
        int target = 4;
        int completed = summary.getTotalWorkoutsCompleted() % 7; // simplistic weekly view
        double pct = target > 0 ? (double) completed / target : 0.0;
        return DashboardData.builder().userName(name).greeting(greeting).currentWorkout(DashboardData.WorkoutSummary.builder().name("Today\'s Workout").duration("45 min").exerciseCount(6).workoutDay("Day 1 of " + target).build()).weeklyCompletion(DashboardData.WeeklyCompletion.builder().completed(completed).target(target).percentage(pct).build()).stats(DashboardData.Stats.builder().caloriesBurned(summary.getCaloriesBurnedDisplay()).activeMinutes(summary.getActiveMinutesDisplay()).streak(summary.getStreakDisplay()).build()).upcomingMeal(DashboardData.UpcomingMeal.builder().name("Today\'s Meal Plan").details("Check your nutrition tab").build()).recommendationStatus(recStatus).aiCoachAvailable(true).build();
    }

    private String getGreeting() {
        int hour = LocalTime.now().getHour();
        if (hour < 12) return "Good Morning";
        if (hour < 17) return "Good Afternoon";
        return "Good Evening";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DashboardService(final UserProfileRepository userProfileRepository, final RecommendationRepository recommendationRepository, final ProgressService progressService) {
        this.userProfileRepository = userProfileRepository;
        this.recommendationRepository = recommendationRepository;
        this.progressService = progressService;
    }
}
