// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.dashboard;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import com.aifitness.common.ApiResponse;
import com.aifitness.dashboard.dto.DashboardData;
import com.aifitness.user.User;
import com.aifitness.user.UserRepository;

@RestController
@RequestMapping("/api/v1/dashboard")
public class DashboardController {
    private final DashboardService dashboardService;
    private final UserRepository userRepository;

    @GetMapping
    public ResponseEntity<ApiResponse<DashboardData>> getDashboard() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String email = ((UserDetails) auth.getPrincipal()).getUsername();
        User user = userRepository.findByEmail(email).orElseThrow(() -> new RuntimeException("User not found"));
        DashboardData data = dashboardService.getDashboard(user.getId());
        return ResponseEntity.ok(ApiResponse.success(data, "Dashboard loaded"));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DashboardController(final DashboardService dashboardService, final UserRepository userRepository) {
        this.dashboardService = dashboardService;
        this.userRepository = userRepository;
    }
}
