// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.form_analysis.dto;

public class FormAnalysisResponse {
    private String status;
    private String message;
    private String exerciseCode;
    private int score;
    private String feedback;
    private String videoUrl;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class FormAnalysisResponseBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String message;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String exerciseCode;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int score;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String feedback;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String videoUrl;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        FormAnalysisResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FormAnalysisResponse.FormAnalysisResponseBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FormAnalysisResponse.FormAnalysisResponseBuilder message(final String message) {
            this.message = message;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FormAnalysisResponse.FormAnalysisResponseBuilder exerciseCode(final String exerciseCode) {
            this.exerciseCode = exerciseCode;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FormAnalysisResponse.FormAnalysisResponseBuilder score(final int score) {
            this.score = score;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FormAnalysisResponse.FormAnalysisResponseBuilder feedback(final String feedback) {
            this.feedback = feedback;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FormAnalysisResponse.FormAnalysisResponseBuilder videoUrl(final String videoUrl) {
            this.videoUrl = videoUrl;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public FormAnalysisResponse build() {
            return new FormAnalysisResponse(this.status, this.message, this.exerciseCode, this.score, this.feedback, this.videoUrl);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "FormAnalysisResponse.FormAnalysisResponseBuilder(status=" + this.status + ", message=" + this.message + ", exerciseCode=" + this.exerciseCode + ", score=" + this.score + ", feedback=" + this.feedback + ", videoUrl=" + this.videoUrl + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static FormAnalysisResponse.FormAnalysisResponseBuilder builder() {
        return new FormAnalysisResponse.FormAnalysisResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getExerciseCode() {
        return this.exerciseCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getScore() {
        return this.score;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFeedback() {
        return this.feedback;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVideoUrl() {
        return this.videoUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExerciseCode(final String exerciseCode) {
        this.exerciseCode = exerciseCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setScore(final int score) {
        this.score = score;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFeedback(final String feedback) {
        this.feedback = feedback;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVideoUrl(final String videoUrl) {
        this.videoUrl = videoUrl;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof FormAnalysisResponse)) return false;
        final FormAnalysisResponse other = (FormAnalysisResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getScore() != other.getScore()) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        final java.lang.Object this$exerciseCode = this.getExerciseCode();
        final java.lang.Object other$exerciseCode = other.getExerciseCode();
        if (this$exerciseCode == null ? other$exerciseCode != null : !this$exerciseCode.equals(other$exerciseCode)) return false;
        final java.lang.Object this$feedback = this.getFeedback();
        final java.lang.Object other$feedback = other.getFeedback();
        if (this$feedback == null ? other$feedback != null : !this$feedback.equals(other$feedback)) return false;
        final java.lang.Object this$videoUrl = this.getVideoUrl();
        final java.lang.Object other$videoUrl = other.getVideoUrl();
        if (this$videoUrl == null ? other$videoUrl != null : !this$videoUrl.equals(other$videoUrl)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof FormAnalysisResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getScore();
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        final java.lang.Object $exerciseCode = this.getExerciseCode();
        result = result * PRIME + ($exerciseCode == null ? 43 : $exerciseCode.hashCode());
        final java.lang.Object $feedback = this.getFeedback();
        result = result * PRIME + ($feedback == null ? 43 : $feedback.hashCode());
        final java.lang.Object $videoUrl = this.getVideoUrl();
        result = result * PRIME + ($videoUrl == null ? 43 : $videoUrl.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "FormAnalysisResponse(status=" + this.getStatus() + ", message=" + this.getMessage() + ", exerciseCode=" + this.getExerciseCode() + ", score=" + this.getScore() + ", feedback=" + this.getFeedback() + ", videoUrl=" + this.getVideoUrl() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public FormAnalysisResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public FormAnalysisResponse(final String status, final String message, final String exerciseCode, final int score, final String feedback, final String videoUrl) {
        this.status = status;
        this.message = message;
        this.exerciseCode = exerciseCode;
        this.score = score;
        this.feedback = feedback;
        this.videoUrl = videoUrl;
    }
}
