// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.groq;

import java.util.List;
import java.util.Map;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

@Service
public class GroqClient {
    private final GroqConfig config;
    private final RestTemplate restTemplate = new RestTemplate();

    public String getChatCompletion(List<Map<String, String>> messages) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.setBearerAuth(config.getApiKey());
        Map<String, Object> requestBody = Map.of("model", config.getModel(), "messages", messages, "temperature", 0.7);
        HttpEntity<Map<String, Object>> entity = new HttpEntity<>(requestBody, headers);
        try {
            var response = restTemplate.postForObject(config.getBaseUrl() + "/chat/completions", entity, GroqResponse.class);
            if (response != null && response.getChoices() != null && !response.getChoices().isEmpty()) {
                return response.getChoices().get(0).getMessage().getContent();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "{}";
    }


    private static class GroqResponse {
        private List<Choice> choices;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public GroqResponse() {
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public List<Choice> getChoices() {
            return this.choices;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setChoices(final List<Choice> choices) {
            this.choices = choices;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof GroqClient.GroqResponse)) return false;
            final GroqClient.GroqResponse other = (GroqClient.GroqResponse) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$choices = this.getChoices();
            final java.lang.Object other$choices = other.getChoices();
            if (this$choices == null ? other$choices != null : !this$choices.equals(other$choices)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof GroqClient.GroqResponse;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $choices = this.getChoices();
            result = result * PRIME + ($choices == null ? 43 : $choices.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "GroqClient.GroqResponse(choices=" + this.getChoices() + ")";
        }
    }


    private static class Choice {
        private Message message;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Choice() {
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Message getMessage() {
            return this.message;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setMessage(final Message message) {
            this.message = message;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof GroqClient.Choice)) return false;
            final GroqClient.Choice other = (GroqClient.Choice) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$message = this.getMessage();
            final java.lang.Object other$message = other.getMessage();
            if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof GroqClient.Choice;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $message = this.getMessage();
            result = result * PRIME + ($message == null ? 43 : $message.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "GroqClient.Choice(message=" + this.getMessage() + ")";
        }
    }


    private static class Message {
        private String role;
        private String content;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Message() {
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getRole() {
            return this.role;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getContent() {
            return this.content;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setRole(final String role) {
            this.role = role;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setContent(final String content) {
            this.content = content;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof GroqClient.Message)) return false;
            final GroqClient.Message other = (GroqClient.Message) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$role = this.getRole();
            final java.lang.Object other$role = other.getRole();
            if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
            final java.lang.Object this$content = this.getContent();
            final java.lang.Object other$content = other.getContent();
            if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof GroqClient.Message;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $role = this.getRole();
            result = result * PRIME + ($role == null ? 43 : $role.hashCode());
            final java.lang.Object $content = this.getContent();
            result = result * PRIME + ($content == null ? 43 : $content.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "GroqClient.Message(role=" + this.getRole() + ", content=" + this.getContent() + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public GroqClient(final GroqConfig config) {
        this.config = config;
    }
}
