// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.groq;

import org.springframework.boot.context.properties.ConfigurationProperties;

@ConfigurationProperties(prefix = "groq")
public class GroqConfig {
    private String apiKey;
    private String model;
    private String baseUrl;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public GroqConfig() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getApiKey() {
        return this.apiKey;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getModel() {
        return this.model;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBaseUrl() {
        return this.baseUrl;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setApiKey(final String apiKey) {
        this.apiKey = apiKey;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setModel(final String model) {
        this.model = model;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBaseUrl(final String baseUrl) {
        this.baseUrl = baseUrl;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof GroqConfig)) return false;
        final GroqConfig other = (GroqConfig) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$apiKey = this.getApiKey();
        final java.lang.Object other$apiKey = other.getApiKey();
        if (this$apiKey == null ? other$apiKey != null : !this$apiKey.equals(other$apiKey)) return false;
        final java.lang.Object this$model = this.getModel();
        final java.lang.Object other$model = other.getModel();
        if (this$model == null ? other$model != null : !this$model.equals(other$model)) return false;
        final java.lang.Object this$baseUrl = this.getBaseUrl();
        final java.lang.Object other$baseUrl = other.getBaseUrl();
        if (this$baseUrl == null ? other$baseUrl != null : !this$baseUrl.equals(other$baseUrl)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof GroqConfig;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $apiKey = this.getApiKey();
        result = result * PRIME + ($apiKey == null ? 43 : $apiKey.hashCode());
        final java.lang.Object $model = this.getModel();
        result = result * PRIME + ($model == null ? 43 : $model.hashCode());
        final java.lang.Object $baseUrl = this.getBaseUrl();
        result = result * PRIME + ($baseUrl == null ? 43 : $baseUrl.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "GroqConfig(apiKey=" + this.getApiKey() + ", model=" + this.getModel() + ", baseUrl=" + this.getBaseUrl() + ")";
    }
}
