// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.user;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

@Entity
@Table(name = "fitness_calculations")
public class FitnessCalculation {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @Column(precision = 6, scale = 2)
    private BigDecimal bmi;
    @Column(precision = 10, scale = 2)
    private BigDecimal bmr;
    @Column(precision = 10, scale = 2)
    private BigDecimal tdee;
    @Column(name = "calorie_target", precision = 10, scale = 2)
    private BigDecimal calorieTarget;
    @Column(name = "protein_target_g", precision = 10, scale = 2)
    private BigDecimal proteinTargetG;
    @Column(name = "carbs_target_g", precision = 10, scale = 2)
    private BigDecimal carbsTargetG;
    @Column(name = "fat_target_g", precision = 10, scale = 2)
    private BigDecimal fatTargetG;
    @Column(name = "calculation_version", nullable = false, length = 30)
    private String calculationVersion = "V1";
    @Column(name = "calculated_at", nullable = false)
    private LocalDateTime calculatedAt;
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        if (calculatedAt == null) {
            calculatedAt = now;
        }
        createdAt = now;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getBmi() {
        return this.bmi;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getBmr() {
        return this.bmr;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getTdee() {
        return this.tdee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getCalorieTarget() {
        return this.calorieTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getProteinTargetG() {
        return this.proteinTargetG;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getCarbsTargetG() {
        return this.carbsTargetG;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getFatTargetG() {
        return this.fatTargetG;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCalculationVersion() {
        return this.calculationVersion;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCalculatedAt() {
        return this.calculatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBmi(final BigDecimal bmi) {
        this.bmi = bmi;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBmr(final BigDecimal bmr) {
        this.bmr = bmr;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTdee(final BigDecimal tdee) {
        this.tdee = tdee;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCalorieTarget(final BigDecimal calorieTarget) {
        this.calorieTarget = calorieTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProteinTargetG(final BigDecimal proteinTargetG) {
        this.proteinTargetG = proteinTargetG;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCarbsTargetG(final BigDecimal carbsTargetG) {
        this.carbsTargetG = carbsTargetG;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFatTargetG(final BigDecimal fatTargetG) {
        this.fatTargetG = fatTargetG;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCalculationVersion(final String calculationVersion) {
        this.calculationVersion = calculationVersion;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCalculatedAt(final LocalDateTime calculatedAt) {
        this.calculatedAt = calculatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof FitnessCalculation)) return false;
        final FitnessCalculation other = (FitnessCalculation) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$bmi = this.getBmi();
        final java.lang.Object other$bmi = other.getBmi();
        if (this$bmi == null ? other$bmi != null : !this$bmi.equals(other$bmi)) return false;
        final java.lang.Object this$bmr = this.getBmr();
        final java.lang.Object other$bmr = other.getBmr();
        if (this$bmr == null ? other$bmr != null : !this$bmr.equals(other$bmr)) return false;
        final java.lang.Object this$tdee = this.getTdee();
        final java.lang.Object other$tdee = other.getTdee();
        if (this$tdee == null ? other$tdee != null : !this$tdee.equals(other$tdee)) return false;
        final java.lang.Object this$calorieTarget = this.getCalorieTarget();
        final java.lang.Object other$calorieTarget = other.getCalorieTarget();
        if (this$calorieTarget == null ? other$calorieTarget != null : !this$calorieTarget.equals(other$calorieTarget)) return false;
        final java.lang.Object this$proteinTargetG = this.getProteinTargetG();
        final java.lang.Object other$proteinTargetG = other.getProteinTargetG();
        if (this$proteinTargetG == null ? other$proteinTargetG != null : !this$proteinTargetG.equals(other$proteinTargetG)) return false;
        final java.lang.Object this$carbsTargetG = this.getCarbsTargetG();
        final java.lang.Object other$carbsTargetG = other.getCarbsTargetG();
        if (this$carbsTargetG == null ? other$carbsTargetG != null : !this$carbsTargetG.equals(other$carbsTargetG)) return false;
        final java.lang.Object this$fatTargetG = this.getFatTargetG();
        final java.lang.Object other$fatTargetG = other.getFatTargetG();
        if (this$fatTargetG == null ? other$fatTargetG != null : !this$fatTargetG.equals(other$fatTargetG)) return false;
        final java.lang.Object this$calculationVersion = this.getCalculationVersion();
        final java.lang.Object other$calculationVersion = other.getCalculationVersion();
        if (this$calculationVersion == null ? other$calculationVersion != null : !this$calculationVersion.equals(other$calculationVersion)) return false;
        final java.lang.Object this$calculatedAt = this.getCalculatedAt();
        final java.lang.Object other$calculatedAt = other.getCalculatedAt();
        if (this$calculatedAt == null ? other$calculatedAt != null : !this$calculatedAt.equals(other$calculatedAt)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof FitnessCalculation;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $bmi = this.getBmi();
        result = result * PRIME + ($bmi == null ? 43 : $bmi.hashCode());
        final java.lang.Object $bmr = this.getBmr();
        result = result * PRIME + ($bmr == null ? 43 : $bmr.hashCode());
        final java.lang.Object $tdee = this.getTdee();
        result = result * PRIME + ($tdee == null ? 43 : $tdee.hashCode());
        final java.lang.Object $calorieTarget = this.getCalorieTarget();
        result = result * PRIME + ($calorieTarget == null ? 43 : $calorieTarget.hashCode());
        final java.lang.Object $proteinTargetG = this.getProteinTargetG();
        result = result * PRIME + ($proteinTargetG == null ? 43 : $proteinTargetG.hashCode());
        final java.lang.Object $carbsTargetG = this.getCarbsTargetG();
        result = result * PRIME + ($carbsTargetG == null ? 43 : $carbsTargetG.hashCode());
        final java.lang.Object $fatTargetG = this.getFatTargetG();
        result = result * PRIME + ($fatTargetG == null ? 43 : $fatTargetG.hashCode());
        final java.lang.Object $calculationVersion = this.getCalculationVersion();
        result = result * PRIME + ($calculationVersion == null ? 43 : $calculationVersion.hashCode());
        final java.lang.Object $calculatedAt = this.getCalculatedAt();
        result = result * PRIME + ($calculatedAt == null ? 43 : $calculatedAt.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "FitnessCalculation(id=" + this.getId() + ", user=" + this.getUser() + ", bmi=" + this.getBmi() + ", bmr=" + this.getBmr() + ", tdee=" + this.getTdee() + ", calorieTarget=" + this.getCalorieTarget() + ", proteinTargetG=" + this.getProteinTargetG() + ", carbsTargetG=" + this.getCarbsTargetG() + ", fatTargetG=" + this.getFatTargetG() + ", calculationVersion=" + this.getCalculationVersion() + ", calculatedAt=" + this.getCalculatedAt() + ", createdAt=" + this.getCreatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public FitnessCalculation() {
    }
}
