// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.user;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

@Entity
@Table(name = "user_goals")
public class UserGoal {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @Column(name = "goal_type", nullable = false, length = 50)
    private String goalType;
    @Column(name = "target_weight_kg", precision = 5, scale = 2)
    private BigDecimal targetWeightKg;
    @Column(name = "target_date")
    private LocalDate targetDate;
    @Column(nullable = false, length = 30)
    private String status = "ACTIVE";
    @Column(name = "started_at", nullable = false)
    private LocalDateTime startedAt;
    @Column(name = "completed_at")
    private LocalDateTime completedAt;
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        if (startedAt == null) {
            startedAt = now;
        }
        createdAt = now;
        updatedAt = now;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGoalType() {
        return this.goalType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getTargetWeightKg() {
        return this.targetWeightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getTargetDate() {
        return this.targetDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getStartedAt() {
        return this.startedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCompletedAt() {
        return this.completedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGoalType(final String goalType) {
        this.goalType = goalType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTargetWeightKg(final BigDecimal targetWeightKg) {
        this.targetWeightKg = targetWeightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTargetDate(final LocalDate targetDate) {
        this.targetDate = targetDate;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStartedAt(final LocalDateTime startedAt) {
        this.startedAt = startedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCompletedAt(final LocalDateTime completedAt) {
        this.completedAt = completedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UserGoal)) return false;
        final UserGoal other = (UserGoal) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$goalType = this.getGoalType();
        final java.lang.Object other$goalType = other.getGoalType();
        if (this$goalType == null ? other$goalType != null : !this$goalType.equals(other$goalType)) return false;
        final java.lang.Object this$targetWeightKg = this.getTargetWeightKg();
        final java.lang.Object other$targetWeightKg = other.getTargetWeightKg();
        if (this$targetWeightKg == null ? other$targetWeightKg != null : !this$targetWeightKg.equals(other$targetWeightKg)) return false;
        final java.lang.Object this$targetDate = this.getTargetDate();
        final java.lang.Object other$targetDate = other.getTargetDate();
        if (this$targetDate == null ? other$targetDate != null : !this$targetDate.equals(other$targetDate)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$startedAt = this.getStartedAt();
        final java.lang.Object other$startedAt = other.getStartedAt();
        if (this$startedAt == null ? other$startedAt != null : !this$startedAt.equals(other$startedAt)) return false;
        final java.lang.Object this$completedAt = this.getCompletedAt();
        final java.lang.Object other$completedAt = other.getCompletedAt();
        if (this$completedAt == null ? other$completedAt != null : !this$completedAt.equals(other$completedAt)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UserGoal;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $goalType = this.getGoalType();
        result = result * PRIME + ($goalType == null ? 43 : $goalType.hashCode());
        final java.lang.Object $targetWeightKg = this.getTargetWeightKg();
        result = result * PRIME + ($targetWeightKg == null ? 43 : $targetWeightKg.hashCode());
        final java.lang.Object $targetDate = this.getTargetDate();
        result = result * PRIME + ($targetDate == null ? 43 : $targetDate.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $startedAt = this.getStartedAt();
        result = result * PRIME + ($startedAt == null ? 43 : $startedAt.hashCode());
        final java.lang.Object $completedAt = this.getCompletedAt();
        result = result * PRIME + ($completedAt == null ? 43 : $completedAt.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "UserGoal(id=" + this.getId() + ", user=" + this.getUser() + ", goalType=" + this.getGoalType() + ", targetWeightKg=" + this.getTargetWeightKg() + ", targetDate=" + this.getTargetDate() + ", status=" + this.getStatus() + ", startedAt=" + this.getStartedAt() + ", completedAt=" + this.getCompletedAt() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserGoal() {
    }
}
