// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.user;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

@Entity
@Table(name = "user_foods")
public class UserFood {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @Column(name = "food_code", nullable = false)
    private String foodCode;
    @Column(name = "other_food_detail")
    private String otherFoodDetail;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFoodCode() {
        return this.foodCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getOtherFoodDetail() {
        return this.otherFoodDetail;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFoodCode(final String foodCode) {
        this.foodCode = foodCode;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOtherFoodDetail(final String otherFoodDetail) {
        this.otherFoodDetail = otherFoodDetail;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UserFood)) return false;
        final UserFood other = (UserFood) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$foodCode = this.getFoodCode();
        final java.lang.Object other$foodCode = other.getFoodCode();
        if (this$foodCode == null ? other$foodCode != null : !this$foodCode.equals(other$foodCode)) return false;
        final java.lang.Object this$otherFoodDetail = this.getOtherFoodDetail();
        final java.lang.Object other$otherFoodDetail = other.getOtherFoodDetail();
        if (this$otherFoodDetail == null ? other$otherFoodDetail != null : !this$otherFoodDetail.equals(other$otherFoodDetail)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UserFood;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $foodCode = this.getFoodCode();
        result = result * PRIME + ($foodCode == null ? 43 : $foodCode.hashCode());
        final java.lang.Object $otherFoodDetail = this.getOtherFoodDetail();
        result = result * PRIME + ($otherFoodDetail == null ? 43 : $otherFoodDetail.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "UserFood(id=" + this.getId() + ", user=" + this.getUser() + ", foodCode=" + this.getFoodCode() + ", otherFoodDetail=" + this.getOtherFoodDetail() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserFood() {
    }
}
