// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.user;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

@Entity
@Table(name = "user_profiles")
public class UserProfile {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;
    @Column(name = "full_name", length = 100)
    private String fullName;
    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;
    @Column(name = "gender", length = 30)
    private String gender;
    @Column(name = "height_cm", precision = 5, scale = 2)
    private BigDecimal heightCm;
    @Column(name = "current_weight_kg", precision = 5, scale = 2)
    private BigDecimal currentWeightKg;
    @Column(name = "activity_level", length = 30)
    private String activityLevel;
    @Column(name = "fitness_experience", length = 30)
    private String fitnessExperience;
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFullName() {
        return this.fullName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getDateOfBirth() {
        return this.dateOfBirth;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGender() {
        return this.gender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getHeightCm() {
        return this.heightCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BigDecimal getCurrentWeightKg() {
        return this.currentWeightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getActivityLevel() {
        return this.activityLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFitnessExperience() {
        return this.fitnessExperience;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFullName(final String fullName) {
        this.fullName = fullName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDateOfBirth(final LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGender(final String gender) {
        this.gender = gender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHeightCm(final BigDecimal heightCm) {
        this.heightCm = heightCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCurrentWeightKg(final BigDecimal currentWeightKg) {
        this.currentWeightKg = currentWeightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setActivityLevel(final String activityLevel) {
        this.activityLevel = activityLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFitnessExperience(final String fitnessExperience) {
        this.fitnessExperience = fitnessExperience;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UserProfile)) return false;
        final UserProfile other = (UserProfile) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$fullName = this.getFullName();
        final java.lang.Object other$fullName = other.getFullName();
        if (this$fullName == null ? other$fullName != null : !this$fullName.equals(other$fullName)) return false;
        final java.lang.Object this$dateOfBirth = this.getDateOfBirth();
        final java.lang.Object other$dateOfBirth = other.getDateOfBirth();
        if (this$dateOfBirth == null ? other$dateOfBirth != null : !this$dateOfBirth.equals(other$dateOfBirth)) return false;
        final java.lang.Object this$gender = this.getGender();
        final java.lang.Object other$gender = other.getGender();
        if (this$gender == null ? other$gender != null : !this$gender.equals(other$gender)) return false;
        final java.lang.Object this$heightCm = this.getHeightCm();
        final java.lang.Object other$heightCm = other.getHeightCm();
        if (this$heightCm == null ? other$heightCm != null : !this$heightCm.equals(other$heightCm)) return false;
        final java.lang.Object this$currentWeightKg = this.getCurrentWeightKg();
        final java.lang.Object other$currentWeightKg = other.getCurrentWeightKg();
        if (this$currentWeightKg == null ? other$currentWeightKg != null : !this$currentWeightKg.equals(other$currentWeightKg)) return false;
        final java.lang.Object this$activityLevel = this.getActivityLevel();
        final java.lang.Object other$activityLevel = other.getActivityLevel();
        if (this$activityLevel == null ? other$activityLevel != null : !this$activityLevel.equals(other$activityLevel)) return false;
        final java.lang.Object this$fitnessExperience = this.getFitnessExperience();
        final java.lang.Object other$fitnessExperience = other.getFitnessExperience();
        if (this$fitnessExperience == null ? other$fitnessExperience != null : !this$fitnessExperience.equals(other$fitnessExperience)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UserProfile;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $fullName = this.getFullName();
        result = result * PRIME + ($fullName == null ? 43 : $fullName.hashCode());
        final java.lang.Object $dateOfBirth = this.getDateOfBirth();
        result = result * PRIME + ($dateOfBirth == null ? 43 : $dateOfBirth.hashCode());
        final java.lang.Object $gender = this.getGender();
        result = result * PRIME + ($gender == null ? 43 : $gender.hashCode());
        final java.lang.Object $heightCm = this.getHeightCm();
        result = result * PRIME + ($heightCm == null ? 43 : $heightCm.hashCode());
        final java.lang.Object $currentWeightKg = this.getCurrentWeightKg();
        result = result * PRIME + ($currentWeightKg == null ? 43 : $currentWeightKg.hashCode());
        final java.lang.Object $activityLevel = this.getActivityLevel();
        result = result * PRIME + ($activityLevel == null ? 43 : $activityLevel.hashCode());
        final java.lang.Object $fitnessExperience = this.getFitnessExperience();
        result = result * PRIME + ($fitnessExperience == null ? 43 : $fitnessExperience.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "UserProfile(id=" + this.getId() + ", user=" + this.getUser() + ", fullName=" + this.getFullName() + ", dateOfBirth=" + this.getDateOfBirth() + ", gender=" + this.getGender() + ", heightCm=" + this.getHeightCm() + ", currentWeightKg=" + this.getCurrentWeightKg() + ", activityLevel=" + this.getActivityLevel() + ", fitnessExperience=" + this.getFitnessExperience() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserProfile() {
    }
}
