// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.dashboard.dto;

public class DashboardData {
    private String userName;
    private String greeting;
    private WorkoutSummary currentWorkout;
    private WeeklyCompletion weeklyCompletion;
    private Stats stats;
    private UpcomingMeal upcomingMeal;
    private String recommendationStatus;
    private boolean aiCoachAvailable;


    public static class WorkoutSummary {
        private String name;
        private String duration;
        private int exerciseCount;
        private String workoutDay;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        WorkoutSummary(final String name, final String duration, final int exerciseCount, final String workoutDay) {
            this.name = name;
            this.duration = duration;
            this.exerciseCount = exerciseCount;
            this.workoutDay = workoutDay;
        }


        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static class WorkoutSummaryBuilder {
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String name;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String duration;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private int exerciseCount;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String workoutDay;

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            WorkoutSummaryBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.WorkoutSummary.WorkoutSummaryBuilder name(final String name) {
                this.name = name;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.WorkoutSummary.WorkoutSummaryBuilder duration(final String duration) {
                this.duration = duration;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.WorkoutSummary.WorkoutSummaryBuilder exerciseCount(final int exerciseCount) {
                this.exerciseCount = exerciseCount;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.WorkoutSummary.WorkoutSummaryBuilder workoutDay(final String workoutDay) {
                this.workoutDay = workoutDay;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.WorkoutSummary build() {
                return new DashboardData.WorkoutSummary(this.name, this.duration, this.exerciseCount, this.workoutDay);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public java.lang.String toString() {
                return "DashboardData.WorkoutSummary.WorkoutSummaryBuilder(name=" + this.name + ", duration=" + this.duration + ", exerciseCount=" + this.exerciseCount + ", workoutDay=" + this.workoutDay + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static DashboardData.WorkoutSummary.WorkoutSummaryBuilder builder() {
            return new DashboardData.WorkoutSummary.WorkoutSummaryBuilder();
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getName() {
            return this.name;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getDuration() {
            return this.duration;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int getExerciseCount() {
            return this.exerciseCount;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getWorkoutDay() {
            return this.workoutDay;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setName(final String name) {
            this.name = name;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setDuration(final String duration) {
            this.duration = duration;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setExerciseCount(final int exerciseCount) {
            this.exerciseCount = exerciseCount;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setWorkoutDay(final String workoutDay) {
            this.workoutDay = workoutDay;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof DashboardData.WorkoutSummary)) return false;
            final DashboardData.WorkoutSummary other = (DashboardData.WorkoutSummary) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getExerciseCount() != other.getExerciseCount()) return false;
            final java.lang.Object this$name = this.getName();
            final java.lang.Object other$name = other.getName();
            if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
            final java.lang.Object this$duration = this.getDuration();
            final java.lang.Object other$duration = other.getDuration();
            if (this$duration == null ? other$duration != null : !this$duration.equals(other$duration)) return false;
            final java.lang.Object this$workoutDay = this.getWorkoutDay();
            final java.lang.Object other$workoutDay = other.getWorkoutDay();
            if (this$workoutDay == null ? other$workoutDay != null : !this$workoutDay.equals(other$workoutDay)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof DashboardData.WorkoutSummary;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getExerciseCount();
            final java.lang.Object $name = this.getName();
            result = result * PRIME + ($name == null ? 43 : $name.hashCode());
            final java.lang.Object $duration = this.getDuration();
            result = result * PRIME + ($duration == null ? 43 : $duration.hashCode());
            final java.lang.Object $workoutDay = this.getWorkoutDay();
            result = result * PRIME + ($workoutDay == null ? 43 : $workoutDay.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "DashboardData.WorkoutSummary(name=" + this.getName() + ", duration=" + this.getDuration() + ", exerciseCount=" + this.getExerciseCount() + ", workoutDay=" + this.getWorkoutDay() + ")";
        }
    }


    public static class WeeklyCompletion {
        private int completed;
        private int target;
        private double percentage;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        WeeklyCompletion(final int completed, final int target, final double percentage) {
            this.completed = completed;
            this.target = target;
            this.percentage = percentage;
        }


        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static class WeeklyCompletionBuilder {
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private int completed;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private int target;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private double percentage;

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            WeeklyCompletionBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.WeeklyCompletion.WeeklyCompletionBuilder completed(final int completed) {
                this.completed = completed;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.WeeklyCompletion.WeeklyCompletionBuilder target(final int target) {
                this.target = target;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.WeeklyCompletion.WeeklyCompletionBuilder percentage(final double percentage) {
                this.percentage = percentage;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.WeeklyCompletion build() {
                return new DashboardData.WeeklyCompletion(this.completed, this.target, this.percentage);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public java.lang.String toString() {
                return "DashboardData.WeeklyCompletion.WeeklyCompletionBuilder(completed=" + this.completed + ", target=" + this.target + ", percentage=" + this.percentage + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static DashboardData.WeeklyCompletion.WeeklyCompletionBuilder builder() {
            return new DashboardData.WeeklyCompletion.WeeklyCompletionBuilder();
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int getCompleted() {
            return this.completed;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int getTarget() {
            return this.target;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public double getPercentage() {
            return this.percentage;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setCompleted(final int completed) {
            this.completed = completed;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setTarget(final int target) {
            this.target = target;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setPercentage(final double percentage) {
            this.percentage = percentage;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof DashboardData.WeeklyCompletion)) return false;
            final DashboardData.WeeklyCompletion other = (DashboardData.WeeklyCompletion) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getCompleted() != other.getCompleted()) return false;
            if (this.getTarget() != other.getTarget()) return false;
            if (java.lang.Double.compare(this.getPercentage(), other.getPercentage()) != 0) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof DashboardData.WeeklyCompletion;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getCompleted();
            result = result * PRIME + this.getTarget();
            final long $percentage = java.lang.Double.doubleToLongBits(this.getPercentage());
            result = result * PRIME + (int) ($percentage >>> 32 ^ $percentage);
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "DashboardData.WeeklyCompletion(completed=" + this.getCompleted() + ", target=" + this.getTarget() + ", percentage=" + this.getPercentage() + ")";
        }
    }


    public static class Stats {
        private String caloriesBurned;
        private String activeMinutes;
        private String streak;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        Stats(final String caloriesBurned, final String activeMinutes, final String streak) {
            this.caloriesBurned = caloriesBurned;
            this.activeMinutes = activeMinutes;
            this.streak = streak;
        }


        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static class StatsBuilder {
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String caloriesBurned;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String activeMinutes;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String streak;

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            StatsBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.Stats.StatsBuilder caloriesBurned(final String caloriesBurned) {
                this.caloriesBurned = caloriesBurned;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.Stats.StatsBuilder activeMinutes(final String activeMinutes) {
                this.activeMinutes = activeMinutes;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.Stats.StatsBuilder streak(final String streak) {
                this.streak = streak;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.Stats build() {
                return new DashboardData.Stats(this.caloriesBurned, this.activeMinutes, this.streak);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public java.lang.String toString() {
                return "DashboardData.Stats.StatsBuilder(caloriesBurned=" + this.caloriesBurned + ", activeMinutes=" + this.activeMinutes + ", streak=" + this.streak + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static DashboardData.Stats.StatsBuilder builder() {
            return new DashboardData.Stats.StatsBuilder();
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getCaloriesBurned() {
            return this.caloriesBurned;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getActiveMinutes() {
            return this.activeMinutes;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getStreak() {
            return this.streak;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setCaloriesBurned(final String caloriesBurned) {
            this.caloriesBurned = caloriesBurned;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setActiveMinutes(final String activeMinutes) {
            this.activeMinutes = activeMinutes;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setStreak(final String streak) {
            this.streak = streak;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof DashboardData.Stats)) return false;
            final DashboardData.Stats other = (DashboardData.Stats) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$caloriesBurned = this.getCaloriesBurned();
            final java.lang.Object other$caloriesBurned = other.getCaloriesBurned();
            if (this$caloriesBurned == null ? other$caloriesBurned != null : !this$caloriesBurned.equals(other$caloriesBurned)) return false;
            final java.lang.Object this$activeMinutes = this.getActiveMinutes();
            final java.lang.Object other$activeMinutes = other.getActiveMinutes();
            if (this$activeMinutes == null ? other$activeMinutes != null : !this$activeMinutes.equals(other$activeMinutes)) return false;
            final java.lang.Object this$streak = this.getStreak();
            final java.lang.Object other$streak = other.getStreak();
            if (this$streak == null ? other$streak != null : !this$streak.equals(other$streak)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof DashboardData.Stats;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $caloriesBurned = this.getCaloriesBurned();
            result = result * PRIME + ($caloriesBurned == null ? 43 : $caloriesBurned.hashCode());
            final java.lang.Object $activeMinutes = this.getActiveMinutes();
            result = result * PRIME + ($activeMinutes == null ? 43 : $activeMinutes.hashCode());
            final java.lang.Object $streak = this.getStreak();
            result = result * PRIME + ($streak == null ? 43 : $streak.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "DashboardData.Stats(caloriesBurned=" + this.getCaloriesBurned() + ", activeMinutes=" + this.getActiveMinutes() + ", streak=" + this.getStreak() + ")";
        }
    }


    public static class UpcomingMeal {
        private String name;
        private String details;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        UpcomingMeal(final String name, final String details) {
            this.name = name;
            this.details = details;
        }


        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static class UpcomingMealBuilder {
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String name;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String details;

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            UpcomingMealBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.UpcomingMeal.UpcomingMealBuilder name(final String name) {
                this.name = name;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.UpcomingMeal.UpcomingMealBuilder details(final String details) {
                this.details = details;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public DashboardData.UpcomingMeal build() {
                return new DashboardData.UpcomingMeal(this.name, this.details);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public java.lang.String toString() {
                return "DashboardData.UpcomingMeal.UpcomingMealBuilder(name=" + this.name + ", details=" + this.details + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static DashboardData.UpcomingMeal.UpcomingMealBuilder builder() {
            return new DashboardData.UpcomingMeal.UpcomingMealBuilder();
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getName() {
            return this.name;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getDetails() {
            return this.details;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setName(final String name) {
            this.name = name;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setDetails(final String details) {
            this.details = details;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof DashboardData.UpcomingMeal)) return false;
            final DashboardData.UpcomingMeal other = (DashboardData.UpcomingMeal) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$name = this.getName();
            final java.lang.Object other$name = other.getName();
            if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
            final java.lang.Object this$details = this.getDetails();
            final java.lang.Object other$details = other.getDetails();
            if (this$details == null ? other$details != null : !this$details.equals(other$details)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof DashboardData.UpcomingMeal;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $name = this.getName();
            result = result * PRIME + ($name == null ? 43 : $name.hashCode());
            final java.lang.Object $details = this.getDetails();
            result = result * PRIME + ($details == null ? 43 : $details.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "DashboardData.UpcomingMeal(name=" + this.getName() + ", details=" + this.getDetails() + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    DashboardData(final String userName, final String greeting, final WorkoutSummary currentWorkout, final WeeklyCompletion weeklyCompletion, final Stats stats, final UpcomingMeal upcomingMeal, final String recommendationStatus, final boolean aiCoachAvailable) {
        this.userName = userName;
        this.greeting = greeting;
        this.currentWorkout = currentWorkout;
        this.weeklyCompletion = weeklyCompletion;
        this.stats = stats;
        this.upcomingMeal = upcomingMeal;
        this.recommendationStatus = recommendationStatus;
        this.aiCoachAvailable = aiCoachAvailable;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class DashboardDataBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String userName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String greeting;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private WorkoutSummary currentWorkout;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private WeeklyCompletion weeklyCompletion;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Stats stats;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private UpcomingMeal upcomingMeal;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String recommendationStatus;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean aiCoachAvailable;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        DashboardDataBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DashboardData.DashboardDataBuilder userName(final String userName) {
            this.userName = userName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DashboardData.DashboardDataBuilder greeting(final String greeting) {
            this.greeting = greeting;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DashboardData.DashboardDataBuilder currentWorkout(final WorkoutSummary currentWorkout) {
            this.currentWorkout = currentWorkout;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DashboardData.DashboardDataBuilder weeklyCompletion(final WeeklyCompletion weeklyCompletion) {
            this.weeklyCompletion = weeklyCompletion;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DashboardData.DashboardDataBuilder stats(final Stats stats) {
            this.stats = stats;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DashboardData.DashboardDataBuilder upcomingMeal(final UpcomingMeal upcomingMeal) {
            this.upcomingMeal = upcomingMeal;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DashboardData.DashboardDataBuilder recommendationStatus(final String recommendationStatus) {
            this.recommendationStatus = recommendationStatus;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DashboardData.DashboardDataBuilder aiCoachAvailable(final boolean aiCoachAvailable) {
            this.aiCoachAvailable = aiCoachAvailable;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public DashboardData build() {
            return new DashboardData(this.userName, this.greeting, this.currentWorkout, this.weeklyCompletion, this.stats, this.upcomingMeal, this.recommendationStatus, this.aiCoachAvailable);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "DashboardData.DashboardDataBuilder(userName=" + this.userName + ", greeting=" + this.greeting + ", currentWorkout=" + this.currentWorkout + ", weeklyCompletion=" + this.weeklyCompletion + ", stats=" + this.stats + ", upcomingMeal=" + this.upcomingMeal + ", recommendationStatus=" + this.recommendationStatus + ", aiCoachAvailable=" + this.aiCoachAvailable + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static DashboardData.DashboardDataBuilder builder() {
        return new DashboardData.DashboardDataBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getUserName() {
        return this.userName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGreeting() {
        return this.greeting;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public WorkoutSummary getCurrentWorkout() {
        return this.currentWorkout;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public WeeklyCompletion getWeeklyCompletion() {
        return this.weeklyCompletion;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Stats getStats() {
        return this.stats;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UpcomingMeal getUpcomingMeal() {
        return this.upcomingMeal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRecommendationStatus() {
        return this.recommendationStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isAiCoachAvailable() {
        return this.aiCoachAvailable;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUserName(final String userName) {
        this.userName = userName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGreeting(final String greeting) {
        this.greeting = greeting;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCurrentWorkout(final WorkoutSummary currentWorkout) {
        this.currentWorkout = currentWorkout;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWeeklyCompletion(final WeeklyCompletion weeklyCompletion) {
        this.weeklyCompletion = weeklyCompletion;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStats(final Stats stats) {
        this.stats = stats;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUpcomingMeal(final UpcomingMeal upcomingMeal) {
        this.upcomingMeal = upcomingMeal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRecommendationStatus(final String recommendationStatus) {
        this.recommendationStatus = recommendationStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAiCoachAvailable(final boolean aiCoachAvailable) {
        this.aiCoachAvailable = aiCoachAvailable;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DashboardData)) return false;
        final DashboardData other = (DashboardData) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isAiCoachAvailable() != other.isAiCoachAvailable()) return false;
        final java.lang.Object this$userName = this.getUserName();
        final java.lang.Object other$userName = other.getUserName();
        if (this$userName == null ? other$userName != null : !this$userName.equals(other$userName)) return false;
        final java.lang.Object this$greeting = this.getGreeting();
        final java.lang.Object other$greeting = other.getGreeting();
        if (this$greeting == null ? other$greeting != null : !this$greeting.equals(other$greeting)) return false;
        final java.lang.Object this$currentWorkout = this.getCurrentWorkout();
        final java.lang.Object other$currentWorkout = other.getCurrentWorkout();
        if (this$currentWorkout == null ? other$currentWorkout != null : !this$currentWorkout.equals(other$currentWorkout)) return false;
        final java.lang.Object this$weeklyCompletion = this.getWeeklyCompletion();
        final java.lang.Object other$weeklyCompletion = other.getWeeklyCompletion();
        if (this$weeklyCompletion == null ? other$weeklyCompletion != null : !this$weeklyCompletion.equals(other$weeklyCompletion)) return false;
        final java.lang.Object this$stats = this.getStats();
        final java.lang.Object other$stats = other.getStats();
        if (this$stats == null ? other$stats != null : !this$stats.equals(other$stats)) return false;
        final java.lang.Object this$upcomingMeal = this.getUpcomingMeal();
        final java.lang.Object other$upcomingMeal = other.getUpcomingMeal();
        if (this$upcomingMeal == null ? other$upcomingMeal != null : !this$upcomingMeal.equals(other$upcomingMeal)) return false;
        final java.lang.Object this$recommendationStatus = this.getRecommendationStatus();
        final java.lang.Object other$recommendationStatus = other.getRecommendationStatus();
        if (this$recommendationStatus == null ? other$recommendationStatus != null : !this$recommendationStatus.equals(other$recommendationStatus)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DashboardData;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isAiCoachAvailable() ? 79 : 97);
        final java.lang.Object $userName = this.getUserName();
        result = result * PRIME + ($userName == null ? 43 : $userName.hashCode());
        final java.lang.Object $greeting = this.getGreeting();
        result = result * PRIME + ($greeting == null ? 43 : $greeting.hashCode());
        final java.lang.Object $currentWorkout = this.getCurrentWorkout();
        result = result * PRIME + ($currentWorkout == null ? 43 : $currentWorkout.hashCode());
        final java.lang.Object $weeklyCompletion = this.getWeeklyCompletion();
        result = result * PRIME + ($weeklyCompletion == null ? 43 : $weeklyCompletion.hashCode());
        final java.lang.Object $stats = this.getStats();
        result = result * PRIME + ($stats == null ? 43 : $stats.hashCode());
        final java.lang.Object $upcomingMeal = this.getUpcomingMeal();
        result = result * PRIME + ($upcomingMeal == null ? 43 : $upcomingMeal.hashCode());
        final java.lang.Object $recommendationStatus = this.getRecommendationStatus();
        result = result * PRIME + ($recommendationStatus == null ? 43 : $recommendationStatus.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "DashboardData(userName=" + this.getUserName() + ", greeting=" + this.getGreeting() + ", currentWorkout=" + this.getCurrentWorkout() + ", weeklyCompletion=" + this.getWeeklyCompletion() + ", stats=" + this.getStats() + ", upcomingMeal=" + this.getUpcomingMeal() + ", recommendationStatus=" + this.getRecommendationStatus() + ", aiCoachAvailable=" + this.isAiCoachAvailable() + ")";
    }
}
