// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.onboarding.dto;

import java.util.List;

public class OnboardingRequest {
    private String name;
    private Integer age;
    private String gender;
    private Integer heightCm;
    private Integer weightKg;
    private String fitnessGoal;
    private String fitnessLevel;
    private List<String> equipment;
    private List<String> foods;
    private String otherFood;
    private String budget;
    private String customBudget;
    private String workoutFrequency;
    private String preferredDuration;
    private String customDuration;
    private String healthConditions;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OnboardingRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getAge() {
        return this.age;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getGender() {
        return this.gender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getHeightCm() {
        return this.heightCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getWeightKg() {
        return this.weightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFitnessGoal() {
        return this.fitnessGoal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFitnessLevel() {
        return this.fitnessLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<String> getEquipment() {
        return this.equipment;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<String> getFoods() {
        return this.foods;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getOtherFood() {
        return this.otherFood;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getBudget() {
        return this.budget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCustomBudget() {
        return this.customBudget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getWorkoutFrequency() {
        return this.workoutFrequency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPreferredDuration() {
        return this.preferredDuration;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCustomDuration() {
        return this.customDuration;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getHealthConditions() {
        return this.healthConditions;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAge(final Integer age) {
        this.age = age;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGender(final String gender) {
        this.gender = gender;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHeightCm(final Integer heightCm) {
        this.heightCm = heightCm;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWeightKg(final Integer weightKg) {
        this.weightKg = weightKg;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFitnessGoal(final String fitnessGoal) {
        this.fitnessGoal = fitnessGoal;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFitnessLevel(final String fitnessLevel) {
        this.fitnessLevel = fitnessLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEquipment(final List<String> equipment) {
        this.equipment = equipment;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFoods(final List<String> foods) {
        this.foods = foods;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOtherFood(final String otherFood) {
        this.otherFood = otherFood;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setBudget(final String budget) {
        this.budget = budget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomBudget(final String customBudget) {
        this.customBudget = customBudget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWorkoutFrequency(final String workoutFrequency) {
        this.workoutFrequency = workoutFrequency;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPreferredDuration(final String preferredDuration) {
        this.preferredDuration = preferredDuration;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCustomDuration(final String customDuration) {
        this.customDuration = customDuration;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setHealthConditions(final String healthConditions) {
        this.healthConditions = healthConditions;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof OnboardingRequest)) return false;
        final OnboardingRequest other = (OnboardingRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$age = this.getAge();
        final java.lang.Object other$age = other.getAge();
        if (this$age == null ? other$age != null : !this$age.equals(other$age)) return false;
        final java.lang.Object this$heightCm = this.getHeightCm();
        final java.lang.Object other$heightCm = other.getHeightCm();
        if (this$heightCm == null ? other$heightCm != null : !this$heightCm.equals(other$heightCm)) return false;
        final java.lang.Object this$weightKg = this.getWeightKg();
        final java.lang.Object other$weightKg = other.getWeightKg();
        if (this$weightKg == null ? other$weightKg != null : !this$weightKg.equals(other$weightKg)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$gender = this.getGender();
        final java.lang.Object other$gender = other.getGender();
        if (this$gender == null ? other$gender != null : !this$gender.equals(other$gender)) return false;
        final java.lang.Object this$fitnessGoal = this.getFitnessGoal();
        final java.lang.Object other$fitnessGoal = other.getFitnessGoal();
        if (this$fitnessGoal == null ? other$fitnessGoal != null : !this$fitnessGoal.equals(other$fitnessGoal)) return false;
        final java.lang.Object this$fitnessLevel = this.getFitnessLevel();
        final java.lang.Object other$fitnessLevel = other.getFitnessLevel();
        if (this$fitnessLevel == null ? other$fitnessLevel != null : !this$fitnessLevel.equals(other$fitnessLevel)) return false;
        final java.lang.Object this$equipment = this.getEquipment();
        final java.lang.Object other$equipment = other.getEquipment();
        if (this$equipment == null ? other$equipment != null : !this$equipment.equals(other$equipment)) return false;
        final java.lang.Object this$foods = this.getFoods();
        final java.lang.Object other$foods = other.getFoods();
        if (this$foods == null ? other$foods != null : !this$foods.equals(other$foods)) return false;
        final java.lang.Object this$otherFood = this.getOtherFood();
        final java.lang.Object other$otherFood = other.getOtherFood();
        if (this$otherFood == null ? other$otherFood != null : !this$otherFood.equals(other$otherFood)) return false;
        final java.lang.Object this$budget = this.getBudget();
        final java.lang.Object other$budget = other.getBudget();
        if (this$budget == null ? other$budget != null : !this$budget.equals(other$budget)) return false;
        final java.lang.Object this$customBudget = this.getCustomBudget();
        final java.lang.Object other$customBudget = other.getCustomBudget();
        if (this$customBudget == null ? other$customBudget != null : !this$customBudget.equals(other$customBudget)) return false;
        final java.lang.Object this$workoutFrequency = this.getWorkoutFrequency();
        final java.lang.Object other$workoutFrequency = other.getWorkoutFrequency();
        if (this$workoutFrequency == null ? other$workoutFrequency != null : !this$workoutFrequency.equals(other$workoutFrequency)) return false;
        final java.lang.Object this$preferredDuration = this.getPreferredDuration();
        final java.lang.Object other$preferredDuration = other.getPreferredDuration();
        if (this$preferredDuration == null ? other$preferredDuration != null : !this$preferredDuration.equals(other$preferredDuration)) return false;
        final java.lang.Object this$customDuration = this.getCustomDuration();
        final java.lang.Object other$customDuration = other.getCustomDuration();
        if (this$customDuration == null ? other$customDuration != null : !this$customDuration.equals(other$customDuration)) return false;
        final java.lang.Object this$healthConditions = this.getHealthConditions();
        final java.lang.Object other$healthConditions = other.getHealthConditions();
        if (this$healthConditions == null ? other$healthConditions != null : !this$healthConditions.equals(other$healthConditions)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof OnboardingRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $age = this.getAge();
        result = result * PRIME + ($age == null ? 43 : $age.hashCode());
        final java.lang.Object $heightCm = this.getHeightCm();
        result = result * PRIME + ($heightCm == null ? 43 : $heightCm.hashCode());
        final java.lang.Object $weightKg = this.getWeightKg();
        result = result * PRIME + ($weightKg == null ? 43 : $weightKg.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $gender = this.getGender();
        result = result * PRIME + ($gender == null ? 43 : $gender.hashCode());
        final java.lang.Object $fitnessGoal = this.getFitnessGoal();
        result = result * PRIME + ($fitnessGoal == null ? 43 : $fitnessGoal.hashCode());
        final java.lang.Object $fitnessLevel = this.getFitnessLevel();
        result = result * PRIME + ($fitnessLevel == null ? 43 : $fitnessLevel.hashCode());
        final java.lang.Object $equipment = this.getEquipment();
        result = result * PRIME + ($equipment == null ? 43 : $equipment.hashCode());
        final java.lang.Object $foods = this.getFoods();
        result = result * PRIME + ($foods == null ? 43 : $foods.hashCode());
        final java.lang.Object $otherFood = this.getOtherFood();
        result = result * PRIME + ($otherFood == null ? 43 : $otherFood.hashCode());
        final java.lang.Object $budget = this.getBudget();
        result = result * PRIME + ($budget == null ? 43 : $budget.hashCode());
        final java.lang.Object $customBudget = this.getCustomBudget();
        result = result * PRIME + ($customBudget == null ? 43 : $customBudget.hashCode());
        final java.lang.Object $workoutFrequency = this.getWorkoutFrequency();
        result = result * PRIME + ($workoutFrequency == null ? 43 : $workoutFrequency.hashCode());
        final java.lang.Object $preferredDuration = this.getPreferredDuration();
        result = result * PRIME + ($preferredDuration == null ? 43 : $preferredDuration.hashCode());
        final java.lang.Object $customDuration = this.getCustomDuration();
        result = result * PRIME + ($customDuration == null ? 43 : $customDuration.hashCode());
        final java.lang.Object $healthConditions = this.getHealthConditions();
        result = result * PRIME + ($healthConditions == null ? 43 : $healthConditions.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "OnboardingRequest(name=" + this.getName() + ", age=" + this.getAge() + ", gender=" + this.getGender() + ", heightCm=" + this.getHeightCm() + ", weightKg=" + this.getWeightKg() + ", fitnessGoal=" + this.getFitnessGoal() + ", fitnessLevel=" + this.getFitnessLevel() + ", equipment=" + this.getEquipment() + ", foods=" + this.getFoods() + ", otherFood=" + this.getOtherFood() + ", budget=" + this.getBudget() + ", customBudget=" + this.getCustomBudget() + ", workoutFrequency=" + this.getWorkoutFrequency() + ", preferredDuration=" + this.getPreferredDuration() + ", customDuration=" + this.getCustomDuration() + ", healthConditions=" + this.getHealthConditions() + ")";
    }
}
