// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.onboarding.dto;

public class OnboardingResponse {
    private String status; // SAFE | MODIFIED | MEDICAL_REVIEW
    private String riskLevel; // LOW | MODERATE | HIGH
    private Long recommendationId;
    private String message;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    OnboardingResponse(final String status, final String riskLevel, final Long recommendationId, final String message) {
        this.status = status;
        this.riskLevel = riskLevel;
        this.recommendationId = recommendationId;
        this.message = message;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class OnboardingResponseBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String riskLevel;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long recommendationId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String message;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        OnboardingResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public OnboardingResponse.OnboardingResponseBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public OnboardingResponse.OnboardingResponseBuilder riskLevel(final String riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public OnboardingResponse.OnboardingResponseBuilder recommendationId(final Long recommendationId) {
            this.recommendationId = recommendationId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public OnboardingResponse.OnboardingResponseBuilder message(final String message) {
            this.message = message;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public OnboardingResponse build() {
            return new OnboardingResponse(this.status, this.riskLevel, this.recommendationId, this.message);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "OnboardingResponse.OnboardingResponseBuilder(status=" + this.status + ", riskLevel=" + this.riskLevel + ", recommendationId=" + this.recommendationId + ", message=" + this.message + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static OnboardingResponse.OnboardingResponseBuilder builder() {
        return new OnboardingResponse.OnboardingResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRiskLevel() {
        return this.riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getRecommendationId() {
        return this.recommendationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRiskLevel(final String riskLevel) {
        this.riskLevel = riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRecommendationId(final Long recommendationId) {
        this.recommendationId = recommendationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof OnboardingResponse)) return false;
        final OnboardingResponse other = (OnboardingResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$recommendationId = this.getRecommendationId();
        final java.lang.Object other$recommendationId = other.getRecommendationId();
        if (this$recommendationId == null ? other$recommendationId != null : !this$recommendationId.equals(other$recommendationId)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$riskLevel = this.getRiskLevel();
        final java.lang.Object other$riskLevel = other.getRiskLevel();
        if (this$riskLevel == null ? other$riskLevel != null : !this$riskLevel.equals(other$riskLevel)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof OnboardingResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $recommendationId = this.getRecommendationId();
        result = result * PRIME + ($recommendationId == null ? 43 : $recommendationId.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $riskLevel = this.getRiskLevel();
        result = result * PRIME + ($riskLevel == null ? 43 : $riskLevel.hashCode());
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "OnboardingResponse(status=" + this.getStatus() + ", riskLevel=" + this.getRiskLevel() + ", recommendationId=" + this.getRecommendationId() + ", message=" + this.getMessage() + ")";
    }
}
