// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.recommendation.dto;

import java.util.List;

public class PlanResponse {
    private Long id;
    private String status;
    private String riskLevel;
    private String planName;
    private Integer weeks;
    private Integer daysPerWeek;
    private String nutritionTarget;
    private List<PlanExercise> exercises;


    public static class PlanExercise {
        private String name;
        private Integer dayNumber;
        private Integer orderIndex;
        private Integer sets;
        private String reps;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        PlanExercise(final String name, final Integer dayNumber, final Integer orderIndex, final Integer sets, final String reps) {
            this.name = name;
            this.dayNumber = dayNumber;
            this.orderIndex = orderIndex;
            this.sets = sets;
            this.reps = reps;
        }


        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static class PlanExerciseBuilder {
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String name;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private Integer dayNumber;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private Integer orderIndex;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private Integer sets;
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            private String reps;

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            PlanExerciseBuilder() {
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public PlanResponse.PlanExercise.PlanExerciseBuilder name(final String name) {
                this.name = name;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public PlanResponse.PlanExercise.PlanExerciseBuilder dayNumber(final Integer dayNumber) {
                this.dayNumber = dayNumber;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public PlanResponse.PlanExercise.PlanExerciseBuilder orderIndex(final Integer orderIndex) {
                this.orderIndex = orderIndex;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public PlanResponse.PlanExercise.PlanExerciseBuilder sets(final Integer sets) {
                this.sets = sets;
                return this;
            }

            /**
             * @return {@code this}.
             */
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public PlanResponse.PlanExercise.PlanExerciseBuilder reps(final String reps) {
                this.reps = reps;
                return this;
            }

            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public PlanResponse.PlanExercise build() {
                return new PlanResponse.PlanExercise(this.name, this.dayNumber, this.orderIndex, this.sets, this.reps);
            }

            @java.lang.Override
            @java.lang.SuppressWarnings("all")
            @lombok.Generated
            public java.lang.String toString() {
                return "PlanResponse.PlanExercise.PlanExerciseBuilder(name=" + this.name + ", dayNumber=" + this.dayNumber + ", orderIndex=" + this.orderIndex + ", sets=" + this.sets + ", reps=" + this.reps + ")";
            }
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public static PlanResponse.PlanExercise.PlanExerciseBuilder builder() {
            return new PlanResponse.PlanExercise.PlanExerciseBuilder();
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getName() {
            return this.name;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Integer getDayNumber() {
            return this.dayNumber;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Integer getOrderIndex() {
            return this.orderIndex;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Integer getSets() {
            return this.sets;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getReps() {
            return this.reps;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setName(final String name) {
            this.name = name;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setDayNumber(final Integer dayNumber) {
            this.dayNumber = dayNumber;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setOrderIndex(final Integer orderIndex) {
            this.orderIndex = orderIndex;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setSets(final Integer sets) {
            this.sets = sets;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setReps(final String reps) {
            this.reps = reps;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof PlanResponse.PlanExercise)) return false;
            final PlanResponse.PlanExercise other = (PlanResponse.PlanExercise) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$dayNumber = this.getDayNumber();
            final java.lang.Object other$dayNumber = other.getDayNumber();
            if (this$dayNumber == null ? other$dayNumber != null : !this$dayNumber.equals(other$dayNumber)) return false;
            final java.lang.Object this$orderIndex = this.getOrderIndex();
            final java.lang.Object other$orderIndex = other.getOrderIndex();
            if (this$orderIndex == null ? other$orderIndex != null : !this$orderIndex.equals(other$orderIndex)) return false;
            final java.lang.Object this$sets = this.getSets();
            final java.lang.Object other$sets = other.getSets();
            if (this$sets == null ? other$sets != null : !this$sets.equals(other$sets)) return false;
            final java.lang.Object this$name = this.getName();
            final java.lang.Object other$name = other.getName();
            if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
            final java.lang.Object this$reps = this.getReps();
            final java.lang.Object other$reps = other.getReps();
            if (this$reps == null ? other$reps != null : !this$reps.equals(other$reps)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof PlanResponse.PlanExercise;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $dayNumber = this.getDayNumber();
            result = result * PRIME + ($dayNumber == null ? 43 : $dayNumber.hashCode());
            final java.lang.Object $orderIndex = this.getOrderIndex();
            result = result * PRIME + ($orderIndex == null ? 43 : $orderIndex.hashCode());
            final java.lang.Object $sets = this.getSets();
            result = result * PRIME + ($sets == null ? 43 : $sets.hashCode());
            final java.lang.Object $name = this.getName();
            result = result * PRIME + ($name == null ? 43 : $name.hashCode());
            final java.lang.Object $reps = this.getReps();
            result = result * PRIME + ($reps == null ? 43 : $reps.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "PlanResponse.PlanExercise(name=" + this.getName() + ", dayNumber=" + this.getDayNumber() + ", orderIndex=" + this.getOrderIndex() + ", sets=" + this.getSets() + ", reps=" + this.getReps() + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    PlanResponse(final Long id, final String status, final String riskLevel, final String planName, final Integer weeks, final Integer daysPerWeek, final String nutritionTarget, final List<PlanExercise> exercises) {
        this.id = id;
        this.status = status;
        this.riskLevel = riskLevel;
        this.planName = planName;
        this.weeks = weeks;
        this.daysPerWeek = daysPerWeek;
        this.nutritionTarget = nutritionTarget;
        this.exercises = exercises;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class PlanResponseBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String riskLevel;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String planName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer weeks;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Integer daysPerWeek;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String nutritionTarget;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<PlanExercise> exercises;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        PlanResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PlanResponse.PlanResponseBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PlanResponse.PlanResponseBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PlanResponse.PlanResponseBuilder riskLevel(final String riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PlanResponse.PlanResponseBuilder planName(final String planName) {
            this.planName = planName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PlanResponse.PlanResponseBuilder weeks(final Integer weeks) {
            this.weeks = weeks;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PlanResponse.PlanResponseBuilder daysPerWeek(final Integer daysPerWeek) {
            this.daysPerWeek = daysPerWeek;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PlanResponse.PlanResponseBuilder nutritionTarget(final String nutritionTarget) {
            this.nutritionTarget = nutritionTarget;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PlanResponse.PlanResponseBuilder exercises(final List<PlanExercise> exercises) {
            this.exercises = exercises;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public PlanResponse build() {
            return new PlanResponse(this.id, this.status, this.riskLevel, this.planName, this.weeks, this.daysPerWeek, this.nutritionTarget, this.exercises);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "PlanResponse.PlanResponseBuilder(id=" + this.id + ", status=" + this.status + ", riskLevel=" + this.riskLevel + ", planName=" + this.planName + ", weeks=" + this.weeks + ", daysPerWeek=" + this.daysPerWeek + ", nutritionTarget=" + this.nutritionTarget + ", exercises=" + this.exercises + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static PlanResponse.PlanResponseBuilder builder() {
        return new PlanResponse.PlanResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRiskLevel() {
        return this.riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPlanName() {
        return this.planName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getWeeks() {
        return this.weeks;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getDaysPerWeek() {
        return this.daysPerWeek;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getNutritionTarget() {
        return this.nutritionTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<PlanExercise> getExercises() {
        return this.exercises;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRiskLevel(final String riskLevel) {
        this.riskLevel = riskLevel;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPlanName(final String planName) {
        this.planName = planName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWeeks(final Integer weeks) {
        this.weeks = weeks;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDaysPerWeek(final Integer daysPerWeek) {
        this.daysPerWeek = daysPerWeek;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNutritionTarget(final String nutritionTarget) {
        this.nutritionTarget = nutritionTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExercises(final List<PlanExercise> exercises) {
        this.exercises = exercises;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PlanResponse)) return false;
        final PlanResponse other = (PlanResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$weeks = this.getWeeks();
        final java.lang.Object other$weeks = other.getWeeks();
        if (this$weeks == null ? other$weeks != null : !this$weeks.equals(other$weeks)) return false;
        final java.lang.Object this$daysPerWeek = this.getDaysPerWeek();
        final java.lang.Object other$daysPerWeek = other.getDaysPerWeek();
        if (this$daysPerWeek == null ? other$daysPerWeek != null : !this$daysPerWeek.equals(other$daysPerWeek)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$riskLevel = this.getRiskLevel();
        final java.lang.Object other$riskLevel = other.getRiskLevel();
        if (this$riskLevel == null ? other$riskLevel != null : !this$riskLevel.equals(other$riskLevel)) return false;
        final java.lang.Object this$planName = this.getPlanName();
        final java.lang.Object other$planName = other.getPlanName();
        if (this$planName == null ? other$planName != null : !this$planName.equals(other$planName)) return false;
        final java.lang.Object this$nutritionTarget = this.getNutritionTarget();
        final java.lang.Object other$nutritionTarget = other.getNutritionTarget();
        if (this$nutritionTarget == null ? other$nutritionTarget != null : !this$nutritionTarget.equals(other$nutritionTarget)) return false;
        final java.lang.Object this$exercises = this.getExercises();
        final java.lang.Object other$exercises = other.getExercises();
        if (this$exercises == null ? other$exercises != null : !this$exercises.equals(other$exercises)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PlanResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $weeks = this.getWeeks();
        result = result * PRIME + ($weeks == null ? 43 : $weeks.hashCode());
        final java.lang.Object $daysPerWeek = this.getDaysPerWeek();
        result = result * PRIME + ($daysPerWeek == null ? 43 : $daysPerWeek.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $riskLevel = this.getRiskLevel();
        result = result * PRIME + ($riskLevel == null ? 43 : $riskLevel.hashCode());
        final java.lang.Object $planName = this.getPlanName();
        result = result * PRIME + ($planName == null ? 43 : $planName.hashCode());
        final java.lang.Object $nutritionTarget = this.getNutritionTarget();
        result = result * PRIME + ($nutritionTarget == null ? 43 : $nutritionTarget.hashCode());
        final java.lang.Object $exercises = this.getExercises();
        result = result * PRIME + ($exercises == null ? 43 : $exercises.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "PlanResponse(id=" + this.getId() + ", status=" + this.getStatus() + ", riskLevel=" + this.getRiskLevel() + ", planName=" + this.getPlanName() + ", weeks=" + this.getWeeks() + ", daysPerWeek=" + this.getDaysPerWeek() + ", nutritionTarget=" + this.getNutritionTarget() + ", exercises=" + this.getExercises() + ")";
    }
}
