// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.coach;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.aifitness.coach.dto.ChatRequest;
import com.aifitness.coach.dto.ChatResponse;
import com.aifitness.groq.GroqClient;
import com.aifitness.groq.GroqPromptBuilder;
import com.aifitness.health.safety.SafetyKeywords;
import com.aifitness.user.User;
import com.aifitness.user.UserProfile;
import com.aifitness.user.UserProfileRepository;
import com.aifitness.user.UserRepository;

@Service
public class CoachService {
    private final CoachConversationRepository conversationRepository;
    private final UserRepository userRepository;
    private final UserProfileRepository userProfileRepository;
    private final GroqClient groqClient;
    private final GroqPromptBuilder promptBuilder;

    @Transactional
    public ChatResponse chat(Long userId, ChatRequest request) {
        User user = userRepository.findById(userId).orElseThrow(() -> new RuntimeException("User not found"));
        String userMessage = request.getMessage();
        // PRE-FILTER: Check for high-risk keywords before calling Groq
        if (SafetyKeywords.containsHighRiskKeyword(userMessage)) {
            CoachConversation conversation = new CoachConversation();
            conversation.setUser(user);
            conversation.setMessage(userMessage);
            conversation.setStatus("MEDICAL_REVIEW");
            conversation.setResponse("I\'m concerned about what you\'ve described. Please consult a healthcare professional " + "before continuing any exercise. Your safety comes first.");
            conversationRepository.save(conversation);
            return ChatResponse.builder().status("MEDICAL_REVIEW").response(conversation.getResponse()).conversationId(conversation.getId()).build();
        }
        // Build context from user profile
        UserProfile profile = userProfileRepository.findByUserId(userId).orElse(null);
        String context = buildUserContext(profile);
        // Call Groq
        var messages = promptBuilder.buildCoachPrompt(context, userMessage);
        String aiResponse = groqClient.getChatCompletion(messages);
        // Save conversation
        CoachConversation conversation = new CoachConversation();
        conversation.setUser(user);
        conversation.setMessage(userMessage);
        conversation.setResponse(aiResponse);
        conversation.setStatus("SAFE");
        conversationRepository.save(conversation);
        return ChatResponse.builder().status("SAFE").response(aiResponse).conversationId(conversation.getId()).build();
    }

    private String buildUserContext(UserProfile profile) {
        if (profile == null) return "No profile available.";
        return String.format("Name: %s, Goal: %s, Level: %s, Height: %scm, Weight: %skg", profile.getFullName(), "N/A", "N/A", profile.getHeightCm(), profile.getCurrentWeightKg());
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CoachService(final CoachConversationRepository conversationRepository, final UserRepository userRepository, final UserProfileRepository userProfileRepository, final GroqClient groqClient, final GroqPromptBuilder promptBuilder) {
        this.conversationRepository = conversationRepository;
        this.userRepository = userRepository;
        this.userProfileRepository = userProfileRepository;
        this.groqClient = groqClient;
        this.promptBuilder = promptBuilder;
    }
}
