// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.coach;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import com.aifitness.coach.dto.ChatRequest;
import com.aifitness.coach.dto.ChatResponse;
import com.aifitness.common.ApiResponse;
import com.aifitness.user.User;
import com.aifitness.user.UserRepository;
import jakarta.validation.Valid;

@RestController
@RequestMapping("/api/v1/coach")
public class CoachController {
    private final CoachService coachService;
    private final UserRepository userRepository;

    @PostMapping("/chat")
    public ResponseEntity<ApiResponse<ChatResponse>> chat(@Valid @RequestBody ChatRequest request) {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String email = ((UserDetails) auth.getPrincipal()).getUsername();
        User user = userRepository.findByEmail(email).orElseThrow(() -> new RuntimeException("User not found"));
        ChatResponse response = coachService.chat(user.getId(), request);
        return ResponseEntity.ok(ApiResponse.success(response, "AI Coach response ready"));
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CoachController(final CoachService coachService, final UserRepository userRepository) {
        this.coachService = coachService;
        this.userRepository = userRepository;
    }
}
