// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.progress;

import java.time.LocalDate;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.aifitness.progress.dto.ProgressSummary;
import com.aifitness.user.User;
import com.aifitness.user.UserRepository;

@Service
public class ProgressService {
    private final ProgressRepository progressRepository;
    private final UserRepository userRepository;

    @Transactional(readOnly = true)
    public ProgressSummary getSummary(Long userId) {
        List<Progress> history = progressRepository.findAllByUserIdOrderByDateDesc(userId);
        int totalWorkouts = history.stream().mapToInt(Progress::getWorkoutsCompleted).sum();
        int totalCalories = history.stream().mapToInt(Progress::getCaloriesBurned).sum();
        int totalMinutes = history.stream().mapToInt(Progress::getActiveMinutes).sum();
        int streak = history.isEmpty() ? 0 : history.get(0).getStreakDays();
        return ProgressSummary.builder().totalWorkoutsCompleted(totalWorkouts).totalCaloriesBurned(totalCalories).totalActiveMinutes(totalMinutes).currentStreak(streak).caloriesBurnedDisplay(totalCalories + " kcal").activeMinutesDisplay(totalMinutes + " min").streakDisplay(streak + " Days").build();
    }

    @Transactional(readOnly = true)
    public List<Progress> getHistory(Long userId) {
        return progressRepository.findAllByUserIdOrderByDateDesc(userId);
    }

    @Transactional
    public Progress recordProgress(Long userId, int caloriesBurned, int activeMinutes) {
        User user = userRepository.findById(userId).orElseThrow(() -> new RuntimeException("User not found"));
        LocalDate today = LocalDate.now();
        Progress progress = progressRepository.findByUserIdAndDate(userId, today).orElseGet(() -> {
            Progress p = new Progress();
            p.setUser(user);
            p.setDate(today);
            return p;
        });
        progress.setCaloriesBurned(progress.getCaloriesBurned() + caloriesBurned);
        progress.setActiveMinutes(progress.getActiveMinutes() + activeMinutes);
        progress.setWorkoutsCompleted(progress.getWorkoutsCompleted() + 1);
        // Calculate streak
        List<Progress> history = progressRepository.findAllByUserIdOrderByDateDesc(userId);
        int streak = calculateStreak(history, today);
        progress.setStreakDays(streak);
        return progressRepository.save(progress);
    }

    private int calculateStreak(List<Progress> history, LocalDate today) {
        int streak = 1;
        for (int i = 0; i < history.size() - 1; i++) {
            LocalDate current = history.get(i).getDate();
            LocalDate prev = history.get(i + 1).getDate();
            if (current.minusDays(1).equals(prev)) {
                streak++;
            } else {
                break;
            }
        }
        return streak;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProgressService(final ProgressRepository progressRepository, final UserRepository userRepository) {
        this.progressRepository = progressRepository;
        this.userRepository = userRepository;
    }
}
