// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.progress;

import java.time.LocalDate;
import com.aifitness.user.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

@Entity
@Table(name = "progress", uniqueConstraints = @UniqueConstraint(columnNames = {"user_id", "date"}))
public class Progress {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    private LocalDate date;
    @Column(name = "workouts_completed")
    private int workoutsCompleted = 0;
    @Column(name = "calories_burned")
    private int caloriesBurned = 0;
    @Column(name = "active_minutes")
    private int activeMinutes = 0;
    @Column(name = "streak_days")
    private int streakDays = 0;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDate getDate() {
        return this.date;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getWorkoutsCompleted() {
        return this.workoutsCompleted;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getCaloriesBurned() {
        return this.caloriesBurned;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getActiveMinutes() {
        return this.activeMinutes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getStreakDays() {
        return this.streakDays;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDate(final LocalDate date) {
        this.date = date;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWorkoutsCompleted(final int workoutsCompleted) {
        this.workoutsCompleted = workoutsCompleted;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCaloriesBurned(final int caloriesBurned) {
        this.caloriesBurned = caloriesBurned;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setActiveMinutes(final int activeMinutes) {
        this.activeMinutes = activeMinutes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStreakDays(final int streakDays) {
        this.streakDays = streakDays;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Progress)) return false;
        final Progress other = (Progress) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getWorkoutsCompleted() != other.getWorkoutsCompleted()) return false;
        if (this.getCaloriesBurned() != other.getCaloriesBurned()) return false;
        if (this.getActiveMinutes() != other.getActiveMinutes()) return false;
        if (this.getStreakDays() != other.getStreakDays()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$user = this.getUser();
        final java.lang.Object other$user = other.getUser();
        if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
        final java.lang.Object this$date = this.getDate();
        final java.lang.Object other$date = other.getDate();
        if (this$date == null ? other$date != null : !this$date.equals(other$date)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Progress;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getWorkoutsCompleted();
        result = result * PRIME + this.getCaloriesBurned();
        result = result * PRIME + this.getActiveMinutes();
        result = result * PRIME + this.getStreakDays();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $user = this.getUser();
        result = result * PRIME + ($user == null ? 43 : $user.hashCode());
        final java.lang.Object $date = this.getDate();
        result = result * PRIME + ($date == null ? 43 : $date.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Progress(id=" + this.getId() + ", user=" + this.getUser() + ", date=" + this.getDate() + ", workoutsCompleted=" + this.getWorkoutsCompleted() + ", caloriesBurned=" + this.getCaloriesBurned() + ", activeMinutes=" + this.getActiveMinutes() + ", streakDays=" + this.getStreakDays() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Progress() {
    }
}
