// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.auth.dto;

public class AuthResponse {
    private String token;
    private Long userId;
    private String name;
    private boolean onboardingComplete;


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class AuthResponseBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String token;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long userId;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String name;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean onboardingComplete;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        AuthResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AuthResponse.AuthResponseBuilder token(final String token) {
            this.token = token;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AuthResponse.AuthResponseBuilder userId(final Long userId) {
            this.userId = userId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AuthResponse.AuthResponseBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AuthResponse.AuthResponseBuilder onboardingComplete(final boolean onboardingComplete) {
            this.onboardingComplete = onboardingComplete;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public AuthResponse build() {
            return new AuthResponse(this.token, this.userId, this.name, this.onboardingComplete);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "AuthResponse.AuthResponseBuilder(token=" + this.token + ", userId=" + this.userId + ", name=" + this.name + ", onboardingComplete=" + this.onboardingComplete + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static AuthResponse.AuthResponseBuilder builder() {
        return new AuthResponse.AuthResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getToken() {
        return this.token;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isOnboardingComplete() {
        return this.onboardingComplete;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setToken(final String token) {
        this.token = token;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOnboardingComplete(final boolean onboardingComplete) {
        this.onboardingComplete = onboardingComplete;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AuthResponse)) return false;
        final AuthResponse other = (AuthResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isOnboardingComplete() != other.isOnboardingComplete()) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$token = this.getToken();
        final java.lang.Object other$token = other.getToken();
        if (this$token == null ? other$token != null : !this$token.equals(other$token)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AuthResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isOnboardingComplete() ? 79 : 97);
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $token = this.getToken();
        result = result * PRIME + ($token == null ? 43 : $token.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "AuthResponse(token=" + this.getToken() + ", userId=" + this.getUserId() + ", name=" + this.getName() + ", onboardingComplete=" + this.isOnboardingComplete() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AuthResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AuthResponse(final String token, final Long userId, final String name, final boolean onboardingComplete) {
        this.token = token;
        this.userId = userId;
        this.name = name;
        this.onboardingComplete = onboardingComplete;
    }
}
