// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.progress.dto;

public class ProgressSummary {
    private int totalWorkoutsCompleted;
    private int totalCaloriesBurned;
    private int totalActiveMinutes;
    private int currentStreak;
    private String caloriesBurnedDisplay;
    private String activeMinutesDisplay;
    private String streakDisplay;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    ProgressSummary(final int totalWorkoutsCompleted, final int totalCaloriesBurned, final int totalActiveMinutes, final int currentStreak, final String caloriesBurnedDisplay, final String activeMinutesDisplay, final String streakDisplay) {
        this.totalWorkoutsCompleted = totalWorkoutsCompleted;
        this.totalCaloriesBurned = totalCaloriesBurned;
        this.totalActiveMinutes = totalActiveMinutes;
        this.currentStreak = currentStreak;
        this.caloriesBurnedDisplay = caloriesBurnedDisplay;
        this.activeMinutesDisplay = activeMinutesDisplay;
        this.streakDisplay = streakDisplay;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ProgressSummaryBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int totalWorkoutsCompleted;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int totalCaloriesBurned;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int totalActiveMinutes;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int currentStreak;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String caloriesBurnedDisplay;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String activeMinutesDisplay;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String streakDisplay;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ProgressSummaryBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProgressSummary.ProgressSummaryBuilder totalWorkoutsCompleted(final int totalWorkoutsCompleted) {
            this.totalWorkoutsCompleted = totalWorkoutsCompleted;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProgressSummary.ProgressSummaryBuilder totalCaloriesBurned(final int totalCaloriesBurned) {
            this.totalCaloriesBurned = totalCaloriesBurned;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProgressSummary.ProgressSummaryBuilder totalActiveMinutes(final int totalActiveMinutes) {
            this.totalActiveMinutes = totalActiveMinutes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProgressSummary.ProgressSummaryBuilder currentStreak(final int currentStreak) {
            this.currentStreak = currentStreak;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProgressSummary.ProgressSummaryBuilder caloriesBurnedDisplay(final String caloriesBurnedDisplay) {
            this.caloriesBurnedDisplay = caloriesBurnedDisplay;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProgressSummary.ProgressSummaryBuilder activeMinutesDisplay(final String activeMinutesDisplay) {
            this.activeMinutesDisplay = activeMinutesDisplay;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProgressSummary.ProgressSummaryBuilder streakDisplay(final String streakDisplay) {
            this.streakDisplay = streakDisplay;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ProgressSummary build() {
            return new ProgressSummary(this.totalWorkoutsCompleted, this.totalCaloriesBurned, this.totalActiveMinutes, this.currentStreak, this.caloriesBurnedDisplay, this.activeMinutesDisplay, this.streakDisplay);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ProgressSummary.ProgressSummaryBuilder(totalWorkoutsCompleted=" + this.totalWorkoutsCompleted + ", totalCaloriesBurned=" + this.totalCaloriesBurned + ", totalActiveMinutes=" + this.totalActiveMinutes + ", currentStreak=" + this.currentStreak + ", caloriesBurnedDisplay=" + this.caloriesBurnedDisplay + ", activeMinutesDisplay=" + this.activeMinutesDisplay + ", streakDisplay=" + this.streakDisplay + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static ProgressSummary.ProgressSummaryBuilder builder() {
        return new ProgressSummary.ProgressSummaryBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getTotalWorkoutsCompleted() {
        return this.totalWorkoutsCompleted;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getTotalCaloriesBurned() {
        return this.totalCaloriesBurned;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getTotalActiveMinutes() {
        return this.totalActiveMinutes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getCurrentStreak() {
        return this.currentStreak;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getCaloriesBurnedDisplay() {
        return this.caloriesBurnedDisplay;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getActiveMinutesDisplay() {
        return this.activeMinutesDisplay;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStreakDisplay() {
        return this.streakDisplay;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotalWorkoutsCompleted(final int totalWorkoutsCompleted) {
        this.totalWorkoutsCompleted = totalWorkoutsCompleted;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotalCaloriesBurned(final int totalCaloriesBurned) {
        this.totalCaloriesBurned = totalCaloriesBurned;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setTotalActiveMinutes(final int totalActiveMinutes) {
        this.totalActiveMinutes = totalActiveMinutes;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCurrentStreak(final int currentStreak) {
        this.currentStreak = currentStreak;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCaloriesBurnedDisplay(final String caloriesBurnedDisplay) {
        this.caloriesBurnedDisplay = caloriesBurnedDisplay;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setActiveMinutesDisplay(final String activeMinutesDisplay) {
        this.activeMinutesDisplay = activeMinutesDisplay;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStreakDisplay(final String streakDisplay) {
        this.streakDisplay = streakDisplay;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ProgressSummary)) return false;
        final ProgressSummary other = (ProgressSummary) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getTotalWorkoutsCompleted() != other.getTotalWorkoutsCompleted()) return false;
        if (this.getTotalCaloriesBurned() != other.getTotalCaloriesBurned()) return false;
        if (this.getTotalActiveMinutes() != other.getTotalActiveMinutes()) return false;
        if (this.getCurrentStreak() != other.getCurrentStreak()) return false;
        final java.lang.Object this$caloriesBurnedDisplay = this.getCaloriesBurnedDisplay();
        final java.lang.Object other$caloriesBurnedDisplay = other.getCaloriesBurnedDisplay();
        if (this$caloriesBurnedDisplay == null ? other$caloriesBurnedDisplay != null : !this$caloriesBurnedDisplay.equals(other$caloriesBurnedDisplay)) return false;
        final java.lang.Object this$activeMinutesDisplay = this.getActiveMinutesDisplay();
        final java.lang.Object other$activeMinutesDisplay = other.getActiveMinutesDisplay();
        if (this$activeMinutesDisplay == null ? other$activeMinutesDisplay != null : !this$activeMinutesDisplay.equals(other$activeMinutesDisplay)) return false;
        final java.lang.Object this$streakDisplay = this.getStreakDisplay();
        final java.lang.Object other$streakDisplay = other.getStreakDisplay();
        if (this$streakDisplay == null ? other$streakDisplay != null : !this$streakDisplay.equals(other$streakDisplay)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ProgressSummary;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getTotalWorkoutsCompleted();
        result = result * PRIME + this.getTotalCaloriesBurned();
        result = result * PRIME + this.getTotalActiveMinutes();
        result = result * PRIME + this.getCurrentStreak();
        final java.lang.Object $caloriesBurnedDisplay = this.getCaloriesBurnedDisplay();
        result = result * PRIME + ($caloriesBurnedDisplay == null ? 43 : $caloriesBurnedDisplay.hashCode());
        final java.lang.Object $activeMinutesDisplay = this.getActiveMinutesDisplay();
        result = result * PRIME + ($activeMinutesDisplay == null ? 43 : $activeMinutesDisplay.hashCode());
        final java.lang.Object $streakDisplay = this.getStreakDisplay();
        result = result * PRIME + ($streakDisplay == null ? 43 : $streakDisplay.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ProgressSummary(totalWorkoutsCompleted=" + this.getTotalWorkoutsCompleted() + ", totalCaloriesBurned=" + this.getTotalCaloriesBurned() + ", totalActiveMinutes=" + this.getTotalActiveMinutes() + ", currentStreak=" + this.getCurrentStreak() + ", caloriesBurnedDisplay=" + this.getCaloriesBurnedDisplay() + ", activeMinutesDisplay=" + this.getActiveMinutesDisplay() + ", streakDisplay=" + this.getStreakDisplay() + ")";
    }
}
