// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.coach.dto;

public class ChatResponse {
    private String status; // SAFE | MEDICAL_REVIEW
    private String response;
    private Long conversationId;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    ChatResponse(final String status, final String response, final Long conversationId) {
        this.status = status;
        this.response = response;
        this.conversationId = conversationId;
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class ChatResponseBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String status;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String response;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long conversationId;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        ChatResponseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ChatResponse.ChatResponseBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ChatResponse.ChatResponseBuilder response(final String response) {
            this.response = response;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ChatResponse.ChatResponseBuilder conversationId(final Long conversationId) {
            this.conversationId = conversationId;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ChatResponse build() {
            return new ChatResponse(this.status, this.response, this.conversationId);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "ChatResponse.ChatResponseBuilder(status=" + this.status + ", response=" + this.response + ", conversationId=" + this.conversationId + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static ChatResponse.ChatResponseBuilder builder() {
        return new ChatResponse.ChatResponseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getResponse() {
        return this.response;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getConversationId() {
        return this.conversationId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setResponse(final String response) {
        this.response = response;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setConversationId(final Long conversationId) {
        this.conversationId = conversationId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ChatResponse)) return false;
        final ChatResponse other = (ChatResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$conversationId = this.getConversationId();
        final java.lang.Object other$conversationId = other.getConversationId();
        if (this$conversationId == null ? other$conversationId != null : !this$conversationId.equals(other$conversationId)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$response = this.getResponse();
        final java.lang.Object other$response = other.getResponse();
        if (this$response == null ? other$response != null : !this$response.equals(other$response)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ChatResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $conversationId = this.getConversationId();
        result = result * PRIME + ($conversationId == null ? 43 : $conversationId.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $response = this.getResponse();
        result = result * PRIME + ($response == null ? 43 : $response.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "ChatResponse(status=" + this.getStatus() + ", response=" + this.getResponse() + ", conversationId=" + this.getConversationId() + ")";
    }
}
