// Generated by delombok at Sun Aug 30 10:11:27 IST 2026
package com.aifitness.onboarding;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.aifitness.health.assessment.UserCondition;
import com.aifitness.health.assessment.UserConditionRepository;
import com.aifitness.health.condition.Condition;
import com.aifitness.health.condition.ConditionRepository;
import com.aifitness.health.risk.RiskEngine;
import com.aifitness.nutrition.NutritionService;
import com.aifitness.onboarding.dto.OnboardingRequest;
import com.aifitness.onboarding.dto.OnboardingResponse;
import com.aifitness.recommendation.Recommendation;
import com.aifitness.recommendation.RecommendationService;
import com.aifitness.user.User;
import com.aifitness.user.UserEquipmentRepository;
import com.aifitness.user.UserFood;
import com.aifitness.user.UserFoodRepository;
import com.aifitness.user.UserGoal;
import com.aifitness.user.UserGoalRepository;
import com.aifitness.user.UserProfile;
import com.aifitness.user.UserProfileRepository;
import com.aifitness.user.UserRepository;

@Service
public class OnboardingService {
    private final UserRepository userRepository;
    private final UserProfileRepository userProfileRepository;
    private final UserEquipmentRepository userEquipmentRepository;
    private final UserFoodRepository userFoodRepository;
    private final UserConditionRepository userConditionRepository;
    private final ConditionRepository conditionRepository;
    private final UserGoalRepository userGoalRepository;
    private final RiskEngine riskEngine;
    private final RecommendationService recommendationService;
    private final NutritionService nutritionService;

    @Transactional
    public OnboardingResponse completeOnboarding(Long userId, OnboardingRequest request) {
        User user = userRepository.findById(userId).orElseThrow(() -> new IllegalArgumentException("User not found"));
        // Save User Goal
        String mappedGoalType = mapGoalType(request.getFitnessGoal());
        java.util.List<UserGoal> activeGoals = userGoalRepository.findByUserIdAndStatus(userId, "ACTIVE");
        UserGoal goal;
        if (!activeGoals.isEmpty()) {
            goal = activeGoals.get(0);
        } else {
            goal = new UserGoal();
            goal.setUser(user);
            goal.setStatus("ACTIVE");
            goal.setStartedAt(java.time.LocalDateTime.now());
        }
        goal.setGoalType(mappedGoalType);
        userGoalRepository.save(goal);
        // Save User Profile
        UserProfile profile = userProfileRepository.findByUserId(userId).orElse(new UserProfile());
        profile.setUser(user);
        profile.setFullName(request.getName());
        if (request.getAge() != null) {
            profile.setDateOfBirth(java.time.LocalDate.now().minusYears(request.getAge()));
        }
        profile.setGender(request.getGender());
        profile.setHeightCm(request.getHeightCm() != null ? java.math.BigDecimal.valueOf(request.getHeightCm()) : null);
        profile.setCurrentWeightKg(request.getWeightKg() != null ? java.math.BigDecimal.valueOf(request.getWeightKg()) : null);
        userProfileRepository.save(profile);
        // Save Equipment
        userEquipmentRepository.deleteAllByUserId(userId);
        if (request.getEquipment() != null) {
            for (String eq : request.getEquipment()) {
                // TODO: Map to Equipment catalog when connecting equipment to onboarding
            }
        }
        // Save Foods
        userFoodRepository.deleteAllByUserId(userId);
        if (request.getFoods() != null) {
            for (String f : request.getFoods()) {
                UserFood food = new UserFood();
                food.setUser(user);
                food.setFoodCode(f);
                if ("OTHER".equalsIgnoreCase(f) || "OtherFood".equalsIgnoreCase(f)) {
                    food.setOtherFoodDetail(request.getOtherFood());
                }
                userFoodRepository.save(food);
            }
        }
        // Mark onboarding complete by saving profile details above
        // Save Health Conditions
        userConditionRepository.deleteAllByUserId(userId);
        if (request.getHealthConditions() != null && !request.getHealthConditions().isBlank()) {
            String[] conditions = request.getHealthConditions().split(",");
            for (String condName : conditions) {
                String trimmedName = condName.trim();
                if (trimmedName.isEmpty()) continue;
                String code = trimmedName.toUpperCase().replace(" ", "_");
                Condition condition = conditionRepository.findByCode(code).orElseGet(() -> {
                    Condition newCond = new Condition();
                    newCond.setCode(code);
                    newCond.setName(trimmedName);
                    newCond.setDefaultRiskLevel("LOW");
                    return conditionRepository.save(newCond);
                });
                UserCondition uc = new UserCondition();
                uc.setUser(user);
                uc.setCondition(condition);
                uc.setSeverity("MODERATE"); // default for now
                userConditionRepository.save(uc);
            }
        }
        // Call Health/Risk Engine
        java.util.List<UserCondition> userConditions = userConditionRepository.findAllByUserId(userId);
        RiskEngine.RiskAssessment assessment = riskEngine.assessRisk(userConditions);
        // Trigger Plan Generation
        Recommendation plan = recommendationService.generatePlan(userId, assessment.riskLevel().name(), assessment.status().name());
        // Save Nutrition Target from Plan
        nutritionService.createOrUpdateTargetFromPlan(plan);
        return OnboardingResponse.builder().status(assessment.status().name()).riskLevel(assessment.riskLevel().name()).recommendationId(plan.getId()).message("Profile saved successfully.").build();
    }

    private String mapGoalType(String rawGoal) {
        if (rawGoal == null) {
            throw new IllegalArgumentException("Fitness goal cannot be empty");
        }
        String normalized = rawGoal.trim().toLowerCase();
        switch (normalized) {
        case "weight loss": 
        case "lose weight": 
        case "weight_loss": 
            return "WEIGHT_LOSS";
        case "weight gain": 
        case "gain weight": 
        case "weight_gain": 
            return "WEIGHT_GAIN";
        case "muscle gain": 
        case "build muscle": 
        case "muscle building": 
        case "muscle_gain": 
            return "MUSCLE_GAIN";
        case "strength": 
        case "build strength": 
            return "STRENGTH";
        case "general fitness": 
        case "fitness": 
        case "get fit": 
        case "general_fitness": 
            return "GENERAL_FITNESS";
        default: 
            String upper = rawGoal.toUpperCase();
            if (upper.equals("WEIGHT_LOSS") || upper.equals("WEIGHT_GAIN") || upper.equals("MUSCLE_GAIN") || upper.equals("STRENGTH") || upper.equals("GENERAL_FITNESS")) {
                return upper;
            }
            throw new IllegalArgumentException("Unsupported fitness goal: " + rawGoal);
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OnboardingService(final UserRepository userRepository, final UserProfileRepository userProfileRepository, final UserEquipmentRepository userEquipmentRepository, final UserFoodRepository userFoodRepository, final UserConditionRepository userConditionRepository, final ConditionRepository conditionRepository, final UserGoalRepository userGoalRepository, final RiskEngine riskEngine, final RecommendationService recommendationService, final NutritionService nutritionService) {
        this.userRepository = userRepository;
        this.userProfileRepository = userProfileRepository;
        this.userEquipmentRepository = userEquipmentRepository;
        this.userFoodRepository = userFoodRepository;
        this.userConditionRepository = userConditionRepository;
        this.conditionRepository = conditionRepository;
        this.userGoalRepository = userGoalRepository;
        this.riskEngine = riskEngine;
        this.recommendationService = recommendationService;
        this.nutritionService = nutritionService;
    }
}
